global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: pige360-api
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [pige360-api:8000]
  - job_name: prometheus
    static_configs:
      - targets: [pige360-prometheus:9090]
