<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from "vue";
import type { Pige360SessionClient } from "@pige360/auth";

type Row=Record<string,any>;
const props=defineProps<{api:Pige360SessionClient}>();const emit=defineEmits<{error:[message:string]}>();
const loading=ref(false);const templates=ref<Row[]>([]);const notifications=ref<Row[]>([]);const people=ref<Row[]>([]);const preferences=ref<Row[]>([]);
const templateForm=reactive({template_key:"",name:"",channel:"internal",subject_template:"",body_template:"",variables:""});
const sendForm=reactive({recipient_person_id:"",channel:"internal",template_id:"",subject:"",body:"",scheduled_at:""});const variables=reactive<Record<string,string>>({});
const selectedTemplate=computed(()=>templates.value.find(x=>x.id===sendForm.template_id));
const selectedVersion=computed(()=>selectedTemplate.value?.versions?.find((x:Row)=>x.version===selectedTemplate.value?.current_version&&x.state==="published"));
const variableNames=computed<string[]>(()=>selectedVersion.value?.variables||[]);
function msg(e:unknown){return e instanceof Error?e.message:"Falha na comunicação";}
function dateBR(v:any){if(!v)return "—";try{return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(String(v)));}catch{return String(v)}}
function idem(prefix:string){return `${prefix}-${crypto.randomUUID()}`;}
watch(()=>sendForm.template_id,()=>{for(const k of Object.keys(variables))delete variables[k];if(selectedTemplate.value)sendForm.channel=selectedTemplate.value.channel;});
async function load(){loading.value=true;try{const [t,n,p,pr]=await Promise.all([props.api.request<Row>("/communication/templates"),props.api.request<Row>("/notifications?limit=100"),props.api.request<Row>("/people"),props.api.request<Row>("/communication/preferences/me").catch(()=>({items:[]}))]);templates.value=t.items||[];notifications.value=n.items||[];people.value=p.items||[];preferences.value=pr.items||[];}catch(e){emit("error",msg(e));}finally{loading.value=false;}}
async function createTemplate(){loading.value=true;try{await props.api.request("/communication/templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...templateForm,subject_template:templateForm.subject_template||null,variables:templateForm.variables.split(",").map(x=>x.trim()).filter(Boolean)})});Object.assign(templateForm,{template_key:"",name:"",channel:"internal",subject_template:"",body_template:"",variables:""});await load();}catch(e){emit("error",msg(e));}finally{loading.value=false;}}
async function publish(row:Row){loading.value=true;try{await props.api.request(`/communication/templates/${row.id}/publish`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_version:row.current_version,reason:"Publicação pelo Branding/Comunicação administrativo"})});await load();}catch(e){emit("error",msg(e));}finally{loading.value=false;}}
async function send(){loading.value=true;try{const template=selectedTemplate.value;const body:any={recipient_person_id:sendForm.recipient_person_id,channel:sendForm.channel,scheduled_at:sendForm.scheduled_at?new Date(sendForm.scheduled_at).toISOString():null};if(template){body.template_key=template.template_key;body.variables={...variables};}else{body.subject=sendForm.subject||null;body.body=sendForm.body;}await props.api.request("/notifications",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":idem("notification")},body:JSON.stringify(body)});Object.assign(sendForm,{recipient_person_id:"",channel:"internal",template_id:"",subject:"",body:"",scheduled_at:""});await load();}catch(e){emit("error",msg(e));}finally{loading.value=false;}}
async function retry(row:Row){loading.value=true;try{await props.api.request(`/notifications/${row.id}/retry`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Retry solicitado pelo administrativo"})});await load();}catch(e){emit("error",msg(e));}finally{loading.value=false;}}
async function cancel(row:Row){loading.value=true;try{await props.api.request(`/notifications/${row.id}/cancel`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Cancelamento solicitado pelo administrativo"})});await load();}catch(e){emit("error",msg(e));}finally{loading.value=false;}}
onMounted(load);
</script>
<template>
  <section class="communication-grid">
    <form class="panel" @submit.prevent="send"><div class="panel-title"><h2>Enviar comunicação</h2><span>fila idempotente</span></div><label>Destinatário<select v-model="sendForm.recipient_person_id" required><option value="">Selecione</option><option v-for="p in people" :key="p.id" :value="p.id">{{p.full_name}} · {{p.email||p.phone||'sem contato externo'}}</option></select></label><label>Template<select v-model="sendForm.template_id"><option value="">Mensagem direta</option><option v-for="t in templates.filter(x=>x.state==='published')" :key="t.id" :value="t.id">{{t.name}} · {{t.channel}}</option></select></label><label v-if="!selectedTemplate">Canal<select v-model="sendForm.channel"><option>internal</option><option>email</option><option>whatsapp</option><option>push</option><option>sms</option></select></label><template v-if="selectedTemplate"><label v-for="v in variableNames" :key="v">{{v}}<input v-model="variables[v]" required /></label></template><template v-else><label>Assunto<input v-model="sendForm.subject" /></label><label>Mensagem<textarea v-model="sendForm.body" rows="5" required></textarea></label></template><label>Agendar para<input v-model="sendForm.scheduled_at" type="datetime-local" /><small>Sem data: entra imediatamente no transactional outbox.</small></label><button class="primary" :disabled="loading">Enfileirar</button></form>
    <form class="panel" @submit.prevent="createTemplate"><div class="panel-title"><h2>Novo template</h2><span>versionado</span></div><label>Chave<input v-model="templateForm.template_key" pattern="[a-z0-9][a-z0-9._-]+" placeholder="finance.due" required /></label><label>Nome<input v-model="templateForm.name" required /></label><label>Canal<select v-model="templateForm.channel"><option>internal</option><option>email</option><option>whatsapp</option><option>push</option><option>sms</option></select></label><label>Assunto<input v-model="templateForm.subject_template" placeholder="Opcional" /></label><label>Corpo<textarea v-model="templateForm.body_template" rows="5" placeholder="Olá {{person.name}}" required></textarea></label><label>Variáveis declaradas<input v-model="templateForm.variables" placeholder="person.name, due_date" /></label><button class="primary" :disabled="loading">Criar rascunho</button></form>
  </section>
  <section class="panel"><div class="panel-title"><h2>Templates</h2><span>{{templates.length}}</span></div><table><thead><tr><th>Template</th><th>Canal</th><th>Versão</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="t in templates" :key="t.id"><td><strong>{{t.name}}</strong><small>{{t.template_key}}</small></td><td>{{t.channel}}</td><td>{{t.current_version}}</td><td><span class="pill" :class="t.state==='published'?'ok':'warn'">{{t.state}}</span></td><td><button v-if="t.state!=='published'" class="small" @click="publish(t)">Publicar</button></td></tr><tr v-if="!templates.length"><td colspan="5" class="empty">Nenhum template cadastrado.</td></tr></tbody></table></section>
  <section class="panel"><div class="panel-title"><h2>Fila e histórico</h2><button class="small" @click="load">Atualizar</button></div><table><thead><tr><th>Data</th><th>Destinatário</th><th>Canal</th><th>Assunto</th><th>Estado</th><th>Tentativas</th><th></th></tr></thead><tbody><tr v-for="n in notifications" :key="n.id"><td>{{dateBR(n.created_at)}}</td><td>{{people.find(x=>x.id===n.recipient_person_id)?.full_name||n.recipient_person_id||'—'}}</td><td>{{n.channel}}</td><td>{{n.subject||n.template_key||'Mensagem'}}</td><td><span class="pill" :class="n.state==='sent'?'ok':n.state==='failed'?'danger':'warn'">{{n.state}}</span></td><td>{{n.attempts}}</td><td class="row-actions"><button v-if="!['sent','cancelled','scheduled'].includes(n.state)" class="small" @click="retry(n)">Retry</button><button v-if="!['sent','cancelled'].includes(n.state)" class="small" @click="cancel(n)">Cancelar</button></td></tr><tr v-if="!notifications.length"><td colspan="7" class="empty">Nenhuma comunicação enfileirada.</td></tr></tbody></table></section>
  <section v-if="preferences.length" class="panel"><div class="panel-title"><h2>Minhas preferências</h2></div><div class="preference-list"><span v-for="p in preferences" :key="p.channel" class="pill" :class="p.enabled?'ok':'warn'">{{p.channel}} · {{p.enabled?'ativo':'desativado'}}</span></div></section>
</template>
<style scoped>
.communication-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:16px}.communication-grid form{display:flex;flex-direction:column;gap:11px}.preference-list{display:flex;flex-wrap:wrap;gap:8px}@media(max-width:900px){.communication-grid{grid-template-columns:1fr}}
</style>
