<script setup lang="ts">
import { onMounted, ref } from "vue";
import type { Pige360SessionClient } from "@pige360/auth";

type Row = Record<string, any>;
type ComposeMode = "new" | "reply" | "forward";
const props = defineProps<{ api: Pige360SessionClient }>();
const emit = defineEmits<{ error:[message:string] }>();
const busy=ref(false); const notice=ref(""); const status=ref<Row|null>(null); const messages=ref<Row[]>([]); const detail=ref<Row|null>(null); const folder=ref("INBOX"); const search=ref(""); const drafts=ref<Row[]>([]); const moveTarget=ref("");
const compose=ref({to:"",cc:"",bcc:"",subject:"",body_text:""}); const composeMode=ref<ComposeMode>("new"); const sourceMessageId=ref<string|null>(null); const replyAll=ref(false);
function problem(e:unknown){const x=e as Error & {problem?:{detail?:string}};return x.problem?.detail||x.message||"Falha no e-mail";}
function emails(value:string){return value.split(/[;,\s]+/).map(x=>x.trim()).filter(Boolean);}
function resetCompose(){compose.value={to:"",cc:"",bcc:"",subject:"",body_text:""};composeMode.value="new";sourceMessageId.value=null;replyAll.value=false;}
async function load(){busy.value=true;try{status.value=await props.api.request<Row>("/mail/me/status");if(!(status.value.folders||[]).some((f:Row)=>f.remote_name===folder.value))folder.value=status.value.folders?.[0]?.remote_name||"INBOX";await Promise.all([loadMessages(),loadDrafts()]);}catch(e){status.value=null;emit("error",problem(e));}finally{busy.value=false;}}
async function sync(){busy.value=true;notice.value="";try{const r=await props.api.request<Row>("/mail/me/sync",{method:"POST"});notice.value=`Sincronização concluída: ${r.messages_synced||0} mensagem(ns).`;await load();}catch(e){emit("error",problem(e));}finally{busy.value=false;}}
async function loadMessages(){try{const q=new URLSearchParams();if(folder.value)q.set("folder",folder.value);if(search.value)q.set("search",search.value);const r=await props.api.request<Row>(`/mail/me/messages?${q}`);messages.value=r.items||[];}catch(e){emit("error",problem(e));}}
async function openMessage(row:Row){try{detail.value=await props.api.request<Row>(`/mail/me/messages/${row.id}`);const flags=Array.isArray(row.flags)?row.flags:[];if(!flags.includes("\\Seen")){await setSeen(true,false);}}catch(e){emit("error",problem(e));}}
async function setSeen(seen:boolean,reload=true){if(!detail.value?.metadata?.id)return;try{await props.api.request(`/mail/me/messages/${detail.value.metadata.id}/seen`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({seen})});notice.value=seen?"Mensagem marcada como lida.":"Mensagem marcada como não lida.";if(reload)await load();}catch(e){emit("error",problem(e));}}
async function moveMessage(destination?:string){if(!detail.value?.metadata?.id)return;const target=destination||moveTarget.value;if(!target)return;busy.value=true;try{await props.api.request(`/mail/me/messages/${detail.value.metadata.id}/move`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({destination_folder:target})});notice.value=`Mensagem movida para ${target}.`;detail.value=null;await load();}catch(e){emit("error",problem(e));}finally{busy.value=false;}}
async function trash(){if(!detail.value?.metadata?.id)return;busy.value=true;try{await props.api.request(`/mail/me/messages/${detail.value.metadata.id}/trash`,{method:"POST"});notice.value="Mensagem movida para a lixeira.";detail.value=null;await load();}catch(e){emit("error",problem(e));}finally{busy.value=false;}}
function beginReply(all=false){if(!detail.value)return;const m=detail.value.metadata||{};const sender=JSON.parse(m.sender_json||"{}");composeMode.value="reply";sourceMessageId.value=m.id;replyAll.value=all;compose.value={to:sender.email||"",cc:"",bcc:"",subject:m.subject||"",body_text:""};}
function beginForward(){if(!detail.value)return;const m=detail.value.metadata||{};composeMode.value="forward";sourceMessageId.value=m.id;replyAll.value=false;compose.value={to:"",cc:"",bcc:"",subject:m.subject||"",body_text:""};}
async function send(){busy.value=true;try{const key=`mail-${crypto.randomUUID()}`;if(composeMode.value==="reply"&&sourceMessageId.value){await props.api.request(`/mail/me/messages/${sourceMessageId.value}/reply`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key},body:JSON.stringify({body_text:compose.value.body_text,reply_all:replyAll.value})});}else if(composeMode.value==="forward"&&sourceMessageId.value){await props.api.request(`/mail/me/messages/${sourceMessageId.value}/forward`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key},body:JSON.stringify({to:emails(compose.value.to),cc:emails(compose.value.cc),bcc:emails(compose.value.bcc),subject:compose.value.subject,body_text:compose.value.body_text})});}else{await props.api.request("/mail/me/send",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key},body:JSON.stringify({to:emails(compose.value.to),cc:emails(compose.value.cc),bcc:emails(compose.value.bcc),subject:compose.value.subject,body_text:compose.value.body_text})});}notice.value="Mensagem enviada.";resetCompose();}catch(e){emit("error",problem(e));}finally{busy.value=false;}}
async function saveDraft(){busy.value=true;try{await props.api.request("/mail/me/drafts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({to:emails(compose.value.to),cc:emails(compose.value.cc),bcc:emails(compose.value.bcc),subject:compose.value.subject,body_text:compose.value.body_text})});notice.value="Rascunho salvo.";await loadDrafts();}catch(e){emit("error",problem(e));}finally{busy.value=false;}}
async function loadDrafts(){try{const r=await props.api.request<Row>("/mail/me/drafts");drafts.value=r.items||[];}catch{drafts.value=[];}}
async function sendDraft(row:Row){busy.value=true;try{await props.api.request(`/mail/me/drafts/${row.id}/send`,{method:"POST",headers:{"Idempotency-Key":`draft-${row.id}-${row.version}`}});notice.value="Rascunho enviado.";await loadDrafts();}catch(e){emit("error",problem(e));}finally{busy.value=false;}}
async function downloadAttachment(index:number,item:Row){if(!detail.value?.metadata?.id)return;try{const response=await props.api.response(`/mail/me/messages/${detail.value.metadata.id}/attachments/${index}`,{headers:{Accept:item.content_type||"application/octet-stream"}});const blob=await response.blob();const expected=response.headers.get("x-content-sha256");if(expected&&crypto.subtle){const digest=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await blob.arrayBuffer()))).map(v=>v.toString(16).padStart(2,"0")).join("");if(digest!==expected)throw new Error("Integridade SHA-256 do anexo inválida");}const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=item.filename||`anexo-${index+1}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){emit("error",problem(e));}}
onMounted(load);
</script>

<template>
  <section class="mail-layout">
    <div v-if="notice" class="mail-ok">{{notice}}</div>
    <div class="mail-toolbar panel">
      <div><h2>Caixa institucional</h2><small v-if="status">{{status.account?.email}} · último sync {{status.account?.last_sync_at ? new Date(status.account.last_sync_at).toLocaleString('pt-BR') : 'ainda não sincronizado'}}</small></div>
      <div class="mail-actions"><button @click="sync" :disabled="busy">Sincronizar</button><button @click="load" :disabled="busy">Atualizar</button></div>
    </div>
    <div v-if="!status" class="panel"><h3>Caixa não configurada</h3><p>Vincule uma mailbox ao usuário em Integrações / Mail antes de usar o cliente interno.</p></div>
    <template v-else>
      <div class="mail-grid">
        <aside class="panel mail-folders"><h3>Pastas</h3><button v-for="f in status.folders||[]" :key="f.id" :class="{active:folder===f.remote_name}" @click="folder=f.remote_name;detail=null;loadMessages()"><span>{{f.display_name}}</span><b v-if="f.unread_count">{{f.unread_count}}</b></button><hr/><h3>Rascunhos</h3><article v-for="d in drafts" :key="d.id"><strong>{{d.subject||'(sem assunto)'}}</strong><small>v{{d.version}}</small><button @click="sendDraft(d)">Enviar</button></article></aside>
        <div class="panel mail-list"><div class="mail-search"><input v-model="search" placeholder="Pesquisar assunto ou prévia" @keyup.enter="loadMessages"/><button @click="loadMessages">Buscar</button></div><button class="mail-item" v-for="m in messages" :key="m.id" @click="openMessage(m)"><span><strong>{{m.sender?.name||m.sender?.email||'Remetente'}}</strong><small>{{m.subject||'(sem assunto)'}}</small><em>{{m.preview}}</em></span><time>{{m.received_at ? new Date(m.received_at).toLocaleString('pt-BR') : ''}}</time></button><p v-if="!messages.length">Nenhuma mensagem nesta pasta.</p></div>
        <div class="panel mail-reader" v-if="detail"><header><h3>{{detail.content?.subject||detail.metadata?.subject}}</h3><small>De: {{detail.content?.sender?.name}} &lt;{{detail.content?.sender?.email}}&gt;</small></header><div class="reader-actions"><button @click="beginReply(false)">Responder</button><button @click="beginReply(true)">Responder a todos</button><button @click="beginForward">Encaminhar</button><button @click="setSeen(false)">Não lida</button><select v-model="moveTarget"><option value="">Mover para…</option><option v-for="f in status.folders||[]" :key="f.id" :value="f.remote_name">{{f.display_name}}</option></select><button :disabled="!moveTarget" @click="moveMessage()">Mover</button><button class="danger" @click="trash">Lixeira</button></div><pre>{{detail.content?.text}}</pre><div v-if="detail.content?.attachments?.length"><h4>Anexos</h4><button class="attachment" v-for="(a,i) in detail.content.attachments" :key="a.sha256" @click="downloadAttachment(i,a)">{{a.filename}} · {{a.size_bytes}} bytes · SHA-256 {{a.sha256}}</button></div></div>
        <form class="panel mail-compose" @submit.prevent="send"><h3>{{composeMode==='reply'?'Responder':composeMode==='forward'?'Encaminhar':'Nova mensagem'}}</h3><button v-if="composeMode!=='new'" type="button" @click="resetCompose">Cancelar {{composeMode==='reply'?'resposta':'encaminhamento'}}</button><label>Para<input v-model="compose.to" :required="composeMode!=='reply'" placeholder="destino@escola.com.br" :disabled="composeMode==='reply'"/></label><label v-if="composeMode!=='reply'">CC<input v-model="compose.cc"/></label><label v-if="composeMode!=='reply'">CCO<input v-model="compose.bcc"/></label><label>Assunto<input v-model="compose.subject" :disabled="composeMode==='reply'"/></label><label>Mensagem<textarea v-model="compose.body_text" rows="10" required></textarea></label><div class="mail-actions"><button v-if="composeMode==='new'" type="button" @click="saveDraft">Salvar rascunho</button><button class="primary" :disabled="busy">Enviar</button></div></form>
      </div>
    </template>
  </section>
</template>

<style scoped>
.mail-layout{display:grid;gap:1rem}.mail-toolbar{display:flex;justify-content:space-between;align-items:center}.mail-actions,.reader-actions{display:flex;gap:.5rem;flex-wrap:wrap}.mail-grid{display:grid;grid-template-columns:220px minmax(280px,1fr) minmax(360px,1.35fr);gap:1rem;align-items:start}.mail-folders{display:grid;gap:.35rem}.mail-folders>button,.mail-item,.attachment{border:0;background:transparent;text-align:left;padding:.65rem;border-radius:.65rem;cursor:pointer}.mail-folders>button.active{background:color-mix(in srgb,var(--brand-primary) 14%,transparent)}.mail-folders>button{display:flex;justify-content:space-between}.mail-folders article{display:grid;gap:.25rem;padding:.5rem 0}.mail-search{display:flex;gap:.5rem;margin-bottom:.75rem}.mail-search input{flex:1}.mail-list{max-height:68vh;overflow:auto}.mail-item{width:100%;display:flex;justify-content:space-between;border-bottom:1px solid #e5e7eb}.mail-item span{display:grid;gap:.15rem}.mail-item em{font-style:normal;opacity:.72}.mail-reader pre{white-space:pre-wrap;font:inherit;line-height:1.55}.reader-actions{margin:.75rem 0}.reader-actions .danger{color:#991b1b}.attachment{display:block;width:100%;border:1px solid #e5e7eb;margin:.35rem 0}.mail-compose{display:grid;gap:.6rem}.mail-compose label{display:grid;gap:.25rem}.mail-ok{padding:.75rem 1rem;border-radius:.6rem;background:#ecfdf5;color:#065f46}@media(max-width:1200px){.mail-grid{grid-template-columns:200px 1fr}.mail-reader,.mail-compose{grid-column:1/-1}}@media(max-width:720px){.mail-grid{grid-template-columns:1fr}.mail-reader,.mail-compose{grid-column:auto}.mail-toolbar{align-items:flex-start;gap:.75rem;flex-direction:column}}
</style>
