[pytest]
addopts = -ra --strict-markers --strict-config -p no:ddtrace
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore:'HTTP_422_UNPROCESSABLE_ENTITY' is deprecated:DeprecationWarning
