<script setup lang="ts">
import { computed,onMounted,reactive,ref } from "vue";
import { Pige360SessionClient, type ApiProblem } from "@pige360/auth";

type Row=Record<string,any>;
const api=new Pige360SessionClient();const ready=ref(false),auth=ref(false),busy=ref(false),error=ref(""),notice=ref("");const privacyNotice=ref<Row|null>(null);const email=ref(""),password=ref("");const ctx=ref<Row>({branding:{},dependents:[],installments:[],bank_accounts:[],notices:[],requests:[],health:{people:[],records:[],incidents:[],medications:[]},canteen_wallets:[],events:[],event_registrations:[],trips:[],consent_purposes:[],privacy_requests:[]});const selected=ref<Row|null>(null);const pix=ref<Row|null>(null);const pendingAuthorization=ref<Row|null>(null);const consentText=ref("Autorizo a participação do meu dependente no evento e declaro ciência das informações apresentadas.");const policyForm=reactive({blocked_allergens:"",blocked_product_ids:"",daily_limit:"",weekly_limit:"",notes:""});const requestForm=reactive({request_type:"administrative",subject:"",description:"",priority:"normal",department:"Secretaria",sla_hours:72});const privacyForm=reactive({request_type:"access",description:""});
const brand=computed(()=>ctx.value.branding||{});const school=computed(()=>brand.value.short_name||brand.value.trade_name||brand.value.legal_name||"Instituição");
function msg(e:unknown){const p=(e as Error&{problem?:ApiProblem})?.problem;return p?.detail||(e instanceof Error?e.message:"Erro inesperado");}function applyBrand(){document.documentElement.style.setProperty("--brand-primary",brand.value.primary_color||"#006D77");document.documentElement.style.setProperty("--brand-secondary",brand.value.secondary_color||"#0D1B2A");document.documentElement.style.setProperty("--brand-accent",brand.value.accent_color||"#F59E0B");document.title=`${school.value} — Família`;}
async function load(){const [portal,health,wallets,events,registrations,trips,purposes,privacyRequests]=await Promise.all([api.request<Row>("/portal/family/me"),api.request<Row>("/health/me").catch(()=>({people:[],records:[],incidents:[],medications:[]})),api.request<Row>("/canteen/wallets/me").catch(()=>({items:[]})),api.request<Row>("/events").catch(()=>({items:[]})),api.request<Row>("/events/me/registrations").catch(()=>({items:[]})),api.request<Row>("/trips/me").catch(()=>({items:[]})),api.request<Row>("/compliance/consent-purposes").catch(()=>({items:[]})),api.request<Row>("/compliance/data-subject-requests").catch(()=>({items:[]}))]);ctx.value={...portal,health,canteen_wallets:wallets.items||[],events:events.items||[],event_registrations:registrations.items||[],trips:trips.items||[],consent_purposes:purposes.items||[],privacy_requests:privacyRequests.items||[]};applyBrand();if(ctx.value.dependents?.length&&!selected.value)await openDependent(ctx.value.dependents[0]);}
async function boot(){try{await api.initialize();auth.value=!!api.tokens;if(auth.value)await load();}catch(e){error.value=msg(e);}finally{ready.value=true;}}
async function login(){busy.value=true;error.value="";try{await api.login(email.value,password.value);auth.value=true;await load();}catch(e){error.value=msg(e);}finally{busy.value=false;}}
async function logout(){await api.logout();auth.value=false;ctx.value={};selected.value=null;pix.value=null;}
async function openDependent(dep:Row){busy.value=true;try{const [base,events,policy,reportCard,daily,pickups,integralization]=await Promise.all([api.request<Row>(`/portal/family/dependents/${dep.student_id}`),api.request<Row>(`/transport/students/${dep.student_id}/events`).catch(()=>({items:[]})),api.request<Row>(`/canteen/students/${dep.student_id}/policy`).catch(()=>({blocked_allergens:[],blocked_product_ids:[],daily_limit:null,weekly_limit:null,notes:null})),api.request<Row>(`/pedagogy/students/${dep.student_id}/report-card`).catch(()=>({enrollments:[]})),api.request<Row>(`/academic/early-childhood/students/${dep.student_id}/daily-records`).catch(()=>({items:[]})),api.request<Row>(`/academic/early-childhood/students/${dep.student_id}/pickups`).catch(()=>({items:[]})),api.request<Row>(`/academic/students/${dep.student_id}/integralization`).catch(()=>({enrollments:[]}))]);const consents=await api.request<Row>(`/compliance/persons/${base.student.person_id}/consents`).catch(()=>({items:[]}));selected.value={...base,transport_events:events.items||[],canteen_policy:policy,report_card:reportCard,daily_records:daily.items||[],pickup_records:pickups.items||[],integralization,consents:consents.items||[]};Object.assign(policyForm,{blocked_allergens:(policy.blocked_allergens||[]).join(", "),blocked_product_ids:(policy.blocked_product_ids||[]).join(", "),daily_limit:policy.daily_limit??"",weekly_limit:policy.weekly_limit??"",notes:policy.notes??""});}catch(e){error.value=msg(e);}finally{busy.value=false;}}
async function generatePix(inst:Row){const account=ctx.value.bank_accounts?.[0];if(!account){error.value="A escola ainda não configurou uma conta PIX ativa.";return;}busy.value=true;try{pix.value=await api.request<Row>(`/banking/accounts/${account.id}/pix-charges`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({installment_id:inst.id})});}catch(e){error.value=msg(e);}finally{busy.value=false;}}
async function copyPix(){if(pix.value?.br_code){await navigator.clipboard.writeText(pix.value.br_code);notice.value="Código PIX copiado.";}}

function walletForSelected(){return ctx.value.canteen_wallets?.find((x:any)=>x.student?.id===selected.value?.student?.id)?.wallet||null;}
function registrationFor(eventId:string){return ctx.value.event_registrations?.find((x:any)=>x.event_id===eventId&&x.student_id===selected.value?.student?.id)||null;}
async function saveFoodPolicy(){if(!selected.value?.student?.id)return;busy.value=true;try{await api.request(`/canteen/students/${selected.value.student.id}/policy`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({blocked_allergens:policyForm.blocked_allergens.split(",").map(x=>x.trim()).filter(Boolean),blocked_product_ids:policyForm.blocked_product_ids.split(",").map(x=>x.trim()).filter(Boolean),daily_limit:policyForm.daily_limit||null,weekly_limit:policyForm.weekly_limit||null,notes:policyForm.notes||null})});notice.value="Política alimentar atualizada.";await openDependent({student_id:selected.value.student.id});}catch(e){error.value=msg(e);}finally{busy.value=false;}}
async function registerEvent(event:Row){if(!selected.value?.student?.id)return;busy.value=true;try{const r=await api.request<Row>(`/events/${event.id}/registrations`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":`event-${crypto.randomUUID()}`},body:JSON.stringify({student_id:selected.value.student.id})});notice.value=r.state==="awaiting_authorization"?"Inscrição reservada; confirme a autorização.":"Inscrição confirmada.";pendingAuthorization.value=r.state==="awaiting_authorization"?r:null;await load();}catch(e){error.value=msg(e);}finally{busy.value=false;}}
async function authorizeEvent(registration:Row){busy.value=true;try{await api.request(`/event-registrations/${registration.id}/authorization`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision:"approved",consent_text:consentText.value})});notice.value="Participação autorizada.";pendingAuthorization.value=null;await load();}catch(e){error.value=msg(e);}finally{busy.value=false;}}
function activeConsent(code:string){return selected.value?.consents?.find((x:any)=>x.purpose_code===code&&x.state==="granted")||null;}async function readPrivacyNotice(purpose:Row){if(!purpose.privacy_notice_id)return;busy.value=true;try{privacyNotice.value=await api.request<Row>(`/compliance/privacy-notices/${purpose.privacy_notice_id}`);}catch(e){error.value=msg(e);}finally{busy.value=false;}}
async function grantConsent(purpose:Row){if(!selected.value?.student?.person_id||!ctx.value.person?.id||!purpose.privacy_notice_id)return;busy.value=true;try{await api.request("/compliance/consents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject_person_id:selected.value.student.person_id,granted_by_person_id:ctx.value.person.id,purpose_code:purpose.code,privacy_notice_id:purpose.privacy_notice_id,channel:"mobile",evidence:{surface:"family-app",affirmative_action:true}})});notice.value="Consentimento registrado.";await openDependent({student_id:selected.value.student.id});}catch(e){error.value=msg(e);}finally{busy.value=false;}}
async function revokeConsent(c:Row){const studentId=selected.value?.student?.id;if(!studentId)return;busy.value=true;try{await api.request(`/compliance/consents/${c.id}/revoke`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Revogação solicitada pelo responsável no Portal da Família"})});notice.value="Consentimento revogado.";await openDependent({student_id:studentId});}catch(e){error.value=msg(e);}finally{busy.value=false;}}
async function createPrivacyRequest(){if(!selected.value?.student?.person_id)return;busy.value=true;try{await api.request("/compliance/data-subject-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject_person_id:selected.value.student.person_id,request_type:privacyForm.request_type,description:privacyForm.description||null,priority:"normal"})});notice.value="Solicitação LGPD registrada.";privacyForm.description="";await load();}catch(e){error.value=msg(e);}finally{busy.value=false;}}
async function createRequest(){busy.value=true;try{await api.request("/service-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(requestForm)});notice.value="Solicitação enviada.";Object.assign(requestForm,{request_type:"administrative",subject:"",description:"",priority:"normal",department:"Secretaria",sla_hours:72});await load();}catch(e){error.value=msg(e);}finally{busy.value=false;}}
function money(v:any){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0));}function date(v:any){if(!v)return"—";return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short"}).format(new Date(v));}
onMounted(boot);
</script>
<template>
<div v-if="!ready" class="center">Carregando portal…</div>
<div v-else-if="!auth" class="login-page"><form class="login-card" @submit.prevent="login"><div class="mark">♡</div><span class="eyebrow">Portal da Família</span><h1>Acesso do responsável</h1><p>Use a conta vinculada aos seus dependentes.</p><label>E-mail<input v-model="email" type="email" required autocomplete="username"></label><label>Senha<input v-model="password" type="password" required autocomplete="current-password"></label><p v-if="error" class="flash error">{{error}}</p><button class="primary" :disabled="busy">Entrar</button></form></div>
<div v-else class="mobile-shell" data-surface="tenant"><header><div class="brand"><div class="mark">♡</div><div><strong>{{school}}</strong><small>Família</small></div></div><button class="ghost" @click="logout">Sair</button></header><main>
<div v-if="error" class="flash error">{{error}}<button @click="error=''">×</button></div><div v-if="notice" class="flash success">{{notice}}<button @click="notice=''">×</button></div>
<section class="welcome"><span>Olá,</span><h1>{{ctx.person?.social_name||ctx.person?.full_name}}</h1><p>Acompanhe vida acadêmica e financeira sem sair do domínio da escola.</p></section>
<section><div class="section-title"><h2>Dependentes</h2><span>{{ctx.dependents?.length||0}}</span></div><div class="cards-scroll"><button v-for="d in ctx.dependents" :key="d.student_id" class="dependent" :class="{active:selected?.student?.id===d.student_id}" @click="openDependent(d)"><strong>{{d.social_name||d.full_name}}</strong><span>{{d.program_name||'Sem programa'}}</span><small>{{d.class_group_name||d.enrollment_state||'Sem turma'}}</small></button></div></section>
<section v-if="selected" class="grid"><article class="metric"><span>Frequência</span><strong>{{selected.attendance?.percentage||'0.00'}}%</strong><small>{{selected.attendance?.counted_sessions||0}} sessões contabilizadas</small></article><article class="metric"><span>Matrícula</span><strong>{{selected.student?.registration_number}}</strong><small>{{selected.enrollments?.[0]?.state||'sem vínculo ativo'}}</small></article></section>
<section v-if="selected" class="panel"><div class="section-title"><h2>Boletim</h2><span>Resultados consolidados</span></div><div v-for="en in selected.report_card?.enrollments||[]" :key="en.enrollment.id" class="report-block"><h3>{{en.enrollment.academic_year_name||en.enrollment.enrollment_number}} · {{en.enrollment.class_name||'Turma'}}</h3><div class="list"><div v-for="r in en.results" :key="r.id" class="list-row"><div><strong>{{r.component_name}}</strong><span>{{r.period_name}} · {{r.outcome}}</span></div><div class="right"><strong>{{Number(r.final_score).toFixed(2)}}</strong><small>Frequência {{Number(r.attendance_percentage).toFixed(2)}}%</small></div></div><p v-if="!en.results?.length" class="empty">Ainda não há resultados pedagógicos consolidados.</p></div></div><p v-if="!selected.report_card?.enrollments?.length" class="empty">Boletim ainda não disponível.</p></section>
<section class="panel"><div class="section-title"><h2>Parcelas</h2><span>{{ctx.installments?.filter((x:any)=>x.state!=='paid').length||0}} abertas</span></div><div class="list"><div v-for="i in ctx.installments" :key="i.id" class="list-row"><div><strong>{{i.student_name||i.description}}</strong><span>Vencimento {{date(i.due_date)}} · {{i.state}}</span></div><div class="right"><strong>{{money(Number(i.original_amount)+Number(i.penalty_amount||0)+Number(i.interest_amount||0)-Number(i.discount_amount||0)-Number(i.paid_amount||0))}}</strong><button v-if="i.state!=='paid'" class="small" @click="generatePix(i)">Gerar PIX</button></div></div><p v-if="!ctx.installments?.length" class="empty">Nenhuma parcela disponível.</p></div></section>
<section v-if="pix" class="panel pix"><div class="section-title"><h2>PIX copia e cola</h2><button class="small" @click="pix=null">Fechar</button></div><strong>{{money(pix.amount)}}</strong><code>{{pix.br_code}}</code><button class="primary" @click="copyPix">Copiar código PIX</button><small>Validade até {{date(pix.expires_at)}}. A baixa depende da confirmação bancária.</small></section>
<section v-if="selected?.daily_records?.length" class="panel"><div class="section-title"><h2>Agenda da Educação Infantil</h2><span>{{selected.daily_records.length}} registros</span></div><div class="list"><div v-for="r in selected.daily_records.slice(0,14)" :key="r.id" class="list-row"><div><strong>{{date(r.record_date)}} · {{r.mood||'Rotina registrada'}}</strong><span v-if="r.development_notes">{{r.development_notes}}</span><small v-if="r.meals?.length">Alimentação: {{r.meals.map((x:any)=>`${x.meal||'refeição'} (${x.consumption||'registrada'})`).join(', ')}}</small><small v-if="r.sleep?.started_at">Sono: {{r.sleep.started_at}} – {{r.sleep.ended_at||'em andamento'}}</small></div><span class="pill">v{{r.version}}</span></div></div><div v-if="selected.pickup_records?.length" class="section-title space"><h3>Retiradas registradas</h3></div><div class="list"><div v-for="p in selected.pickup_records?.slice(0,8)" :key="p.id" class="list-row"><div><strong>{{p.pickup_person_name}}</strong><span>{{p.relationship||'Responsável'}} · {{date(p.released_at)}}</span></div></div></div></section>
<section v-if="selected?.integralization?.enrollments?.some((x:any)=>Number(x.curriculum?.components_total||0)>0)" class="panel"><div class="section-title"><h2>Integralização curricular</h2><span>Técnico / Superior</span></div><div v-for="en in selected.integralization.enrollments" :key="en.enrollment.id" class="report-block"><h3>{{en.enrollment.program_name}} · {{en.enrollment.curriculum_name}}</h3><div class="grid"><article class="metric"><span>Componentes</span><strong>{{en.curriculum.components_completed}}/{{en.curriculum.components_total}}</strong><small>{{en.curriculum.completion_percentage}}% da carga horária</small></article><article class="metric"><span>Atividades complementares</span><strong>{{en.complementary_hours_approved}}h</strong><small>horas homologadas</small></article></div><div class="list"><div v-for="i in en.internships" :key="i.id" class="list-row"><div><strong>Estágio</strong><span>{{i.completed_hours}}/{{i.required_hours}}h · {{i.state}}</span></div></div><div v-for="t in en.theses" :key="t.id" class="list-row"><div><strong>{{t.title}}</strong><span>TCC · {{t.state}}<template v-if="t.grade"> · nota {{t.grade}}</template></span></div></div></div></div></section>
<section v-if="selected" class="grid two"><div class="panel"><div class="section-title"><h2>Transporte</h2><span>{{selected.transport_events?.length||0}} eventos</span></div><div class="list"><div v-for="t in selected.transport_events?.slice(0,8)" :key="t.id" class="list-row"><div><strong>{{t.event_type==='boarded'?'Embarque':t.event_type==='disembarked'?'Desembarque':t.event_type}}</strong><span>{{t.route_name}} · {{t.stop_name||'sem parada informada'}}</span></div><small>{{date(t.occurred_at)}}</small></div><p v-if="!selected.transport_events?.length" class="empty">Sem eventos recentes de transporte.</p></div></div><div class="panel"><div class="section-title"><h2>Saúde autorizada</h2></div><article v-for="i in (ctx.health?.incidents||[]).filter((x:any)=>x.person_id===selected.student?.person_id).slice(0,6)" :key="i.id" class="notice"><strong>{{i.incident_type}}</strong><p>{{i.summary}}</p><small>{{date(i.occurred_at)}} · {{i.state}}</small></article><article v-for="m in (ctx.health?.medications||[]).filter((x:any)=>x.person_id===selected.student?.person_id).slice(0,6)" :key="m.id" class="notice"><strong>{{m.medication_name}} · {{m.dosage}}</strong><p>{{m.instructions}}</p><small>Vigência {{date(m.starts_on)}} a {{date(m.ends_on)}}</small></article><p v-if="!(ctx.health?.incidents||[]).some((x:any)=>x.person_id===selected.student?.person_id)&&!(ctx.health?.medications||[]).some((x:any)=>x.person_id===selected.student?.person_id)" class="empty">Sem ocorrências ou medicações visíveis.</p></div></section>
<section v-if="selected" class="grid two"><div class="panel"><div class="section-title"><h2>Cantina</h2><span>Carteira</span></div><div v-if="walletForSelected()" class="metric-inline"><strong>{{money(walletForSelected().balance)}}</strong><small>saldo disponível · limite diário {{walletForSelected().daily_limit?money(walletForSelected().daily_limit):'não definido'}}</small></div><p v-else class="empty">Carteira ainda não criada pela escola.</p><form class="form compact" @submit.prevent="saveFoodPolicy"><label>Alergênicos/restrições, separados por vírgula<input v-model="policyForm.blocked_allergens" placeholder="amendoim, lactose"></label><div class="cols"><label>Limite diário<input v-model="policyForm.daily_limit" type="number" step="0.01"></label><label>Limite semanal<input v-model="policyForm.weekly_limit" type="number" step="0.01"></label></div><label>Observações<textarea v-model="policyForm.notes" rows="2"></textarea></label><button class="small">Salvar política alimentar</button></form></div><div class="panel"><div class="section-title"><h2>Eventos e viagens</h2><span>{{ctx.events?.length||0}} eventos</span></div><article v-for="e in ctx.events?.slice(0,8)" :key="e.id" class="notice"><strong>{{e.name}}</strong><p>{{e.location||'Local a confirmar'}} · {{date(e.starts_at)}}<br>Taxa: {{money(e.registration_fee||0)}} <span v-if="e.authorization_required">· exige autorização</span></p><div class="row-actions"><span v-if="registrationFor(e.id)" class="pill">{{registrationFor(e.id).state}}</span><button v-else class="small" @click="registerEvent(e)">Inscrever {{selected.student?.social_name||selected.student?.full_name}}</button><button v-if="registrationFor(e.id)?.authorization_state==='pending'" class="small" @click="authorizeEvent(registrationFor(e.id))">Autorizar</button></div></article><div v-for="t in ctx.trips?.filter((x:any)=>x.student_id===selected.student?.id).slice(0,5)" :key="t.id" class="list-row"><div><strong>{{t.trip_name}}</strong><span>{{t.destination}} · {{t.trip_state}}</span></div><small>{{t.state}}</small></div></div></section><section v-if="pendingAuthorization" class="panel"><div class="section-title"><h2>Autorização do responsável</h2><button class="small" @click="pendingAuthorization=null">Fechar</button></div><p>Leia o evento integralmente antes de confirmar. O aceite será registrado com sua conta autenticada, data, correlação e evidência.</p><label>Declaração<textarea v-model="consentText" rows="4"></textarea></label><button class="primary" @click="authorizeEvent(pendingAuthorization)">Confirmar autorização</button></section>
<section v-if="selected" class="grid two"><div class="panel"><div class="section-title"><h2>Privacidade e consentimentos</h2><span>LGPD</span></div><article v-for="p in ctx.consent_purposes" :key="p.code" class="notice"><strong>{{p.name}}</strong><p>{{p.purpose}}</p><small v-if="p.privacy_notice_title">{{p.privacy_notice_title}} · v{{p.privacy_notice_version}}</small><div class="row-actions"><button v-if="p.privacy_notice_id" class="small" @click="readPrivacyNotice(p)">Ler aviso</button><button v-if="!activeConsent(p.code)&&selected.relationship?.is_legal" class="small" :disabled="!p.privacy_notice_id" @click="grantConsent(p)">Autorizar</button><button v-if="activeConsent(p.code)" class="small" @click="revokeConsent(activeConsent(p.code))">Revogar</button></div></article><p v-if="!ctx.consent_purposes?.length" class="empty">Nenhuma finalidade baseada em consentimento está publicada.</p></div><form class="panel form" @submit.prevent="createPrivacyRequest"><h2>Direitos do titular</h2><label>Solicitação<select v-model="privacyForm.request_type"><option value="access">Acesso aos dados</option><option value="export">Exportação</option><option value="rectification">Retificação</option><option value="restriction">Restrição</option><option value="objection">Oposição</option><option value="anonymization">Anonimização</option></select></label><label>Descrição<textarea v-model="privacyForm.description" rows="4" placeholder="Explique o pedido, quando necessário."></textarea></label><button class="primary">Registrar solicitação LGPD</button><small v-for="r in ctx.privacy_requests?.filter((x:any)=>x.subject_person_id===selected.student.person_id).slice(0,5)" :key="r.id">{{r.protocol}} · {{r.request_type}} · {{r.state}}</small></form></section>
<section v-if="privacyNotice" class="panel"><div class="section-title"><h2>{{privacyNotice.title}}</h2><button class="small" @click="privacyNotice=null">Fechar</button></div><small>{{privacyNotice.code}} · v{{privacyNotice.version}} · SHA-256 {{privacyNotice.sha256}}</small><p style="white-space:pre-wrap">{{privacyNotice.content}}</p></section><section class="grid two"><div class="panel"><div class="section-title"><h2>Avisos</h2></div><article v-for="n in ctx.notices?.slice(0,8)" :key="n.id" class="notice"><strong>{{n.title}}</strong><p>{{n.body}}</p><small>{{date(n.created_at)}}</small></article><p v-if="!ctx.notices?.length" class="empty">Sem avisos publicados.</p></div><form class="panel form" @submit.prevent="createRequest"><h2>Nova solicitação</h2><label>Assunto<input v-model="requestForm.subject" required></label><label>Tipo<input v-model="requestForm.request_type" required></label><label>Descrição<textarea v-model="requestForm.description" rows="4"></textarea></label><button class="primary">Abrir protocolo</button><div class="protocols"><small v-for="r in ctx.requests?.slice(0,5)" :key="r.id">{{r.protocol}} · {{r.subject}} · {{r.state}}</small></div></form></section>
</main></div>
</template>
