FROM pige360-api:1.0.0
ARG VERSION=1.0.0
LABEL org.opencontainers.image.title="pige360-reporting" org.opencontainers.image.version="$VERSION"
USER 10001:10001
CMD ["celery","-A","app.worker:celery_app","worker","--loglevel=INFO","--queues=reports"]
