"""Educação infantil, pré-requisitos, estágio, atividades complementares e TCC."""
from alembic import op
revision="0026_education_stage_progress"
down_revision="0025_grading_assessments"
branch_labels=None
depends_on=None
TABLES=("early_childhood_daily_records","student_pickup_records","component_prerequisites","student_component_completions","internships","internship_hour_logs","complementary_activities","theses","thesis_events")
def upgrade():
    op.execute("""CREATE TABLE IF NOT EXISTS early_childhood_daily_records(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,student_id TEXT NOT NULL REFERENCES students(id),unit_id TEXT NOT NULL REFERENCES units(id),record_date DATE NOT NULL,meals_json JSONB NOT NULL DEFAULT '[]'::jsonb,sleep_json JSONB NOT NULL DEFAULT '{}'::jsonb,hygiene_json JSONB NOT NULL DEFAULT '[]'::jsonb,diaper_changes_json JSONB NOT NULL DEFAULT '[]'::jsonb,mood TEXT,development_notes TEXT,authorized_photos_json JSONB NOT NULL DEFAULT '[]'::jsonb,state TEXT NOT NULL DEFAULT 'active',version INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,UNIQUE(tenant_id,student_id,record_date))""")
    op.execute("CREATE INDEX IF NOT EXISTS ix_early_childhood_daily_date ON early_childhood_daily_records(tenant_id,unit_id,record_date)")
    op.execute("""CREATE TABLE IF NOT EXISTS student_pickup_records(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,student_id TEXT NOT NULL REFERENCES students(id),guardian_id TEXT REFERENCES guardians(id),pickup_person_name TEXT NOT NULL,relationship TEXT,identity_document_masked TEXT,released_at TIMESTAMPTZ NOT NULL,released_by TEXT NOT NULL,notes TEXT,created_at TIMESTAMPTZ NOT NULL)""")
    op.execute("CREATE INDEX IF NOT EXISTS ix_student_pickup_student ON student_pickup_records(tenant_id,student_id,released_at)")
    op.execute("""CREATE TABLE IF NOT EXISTS component_prerequisites(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,component_id TEXT NOT NULL REFERENCES curriculum_components(id),prerequisite_component_id TEXT NOT NULL REFERENCES curriculum_components(id),minimum_final_score NUMERIC,state TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL,UNIQUE(tenant_id,component_id,prerequisite_component_id))""")
    op.execute("""CREATE TABLE IF NOT EXISTS student_component_completions(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,enrollment_id TEXT NOT NULL REFERENCES enrollments(id),component_id TEXT NOT NULL REFERENCES curriculum_components(id),source_type TEXT NOT NULL,source_reference_id TEXT,final_score NUMERIC,credits_awarded NUMERIC,workload_hours_awarded NUMERIC,completed_on DATE NOT NULL,state TEXT NOT NULL DEFAULT 'approved',reason TEXT,approved_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,UNIQUE(tenant_id,enrollment_id,component_id,state))""")
    op.execute("""CREATE TABLE IF NOT EXISTS internships(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,enrollment_id TEXT NOT NULL REFERENCES enrollments(id),organization_name TEXT NOT NULL,supervisor_name TEXT,advisor_employee_id TEXT REFERENCES employees(id),starts_on DATE NOT NULL,ends_on DATE,required_hours NUMERIC NOT NULL DEFAULT 0,completed_hours NUMERIC NOT NULL DEFAULT 0,state TEXT NOT NULL DEFAULT 'draft',version INTEGER NOT NULL DEFAULT 1,notes TEXT,created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL)""")
    op.execute("""CREATE TABLE IF NOT EXISTS internship_hour_logs(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,internship_id TEXT NOT NULL REFERENCES internships(id),activity_date DATE NOT NULL,hours NUMERIC NOT NULL,description TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'approved',recorded_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL)""")
    op.execute("""CREATE TABLE IF NOT EXISTS complementary_activities(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,enrollment_id TEXT NOT NULL REFERENCES enrollments(id),category TEXT NOT NULL,title TEXT NOT NULL,requested_hours NUMERIC NOT NULL,approved_hours NUMERIC NOT NULL DEFAULT 0,evidence_document_id TEXT REFERENCES documents(id),state TEXT NOT NULL DEFAULT 'submitted',review_notes TEXT,submitted_by TEXT NOT NULL,reviewed_by TEXT,submitted_at TIMESTAMPTZ NOT NULL,reviewed_at TIMESTAMPTZ)""")
    op.execute("""CREATE TABLE IF NOT EXISTS theses(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,enrollment_id TEXT NOT NULL REFERENCES enrollments(id),title TEXT NOT NULL,advisor_employee_id TEXT REFERENCES employees(id),coadvisor_name TEXT,state TEXT NOT NULL DEFAULT 'proposal',grade NUMERIC,defense_at TIMESTAMPTZ,abstract TEXT,document_id TEXT REFERENCES documents(id),version INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL)""")
    op.execute("""CREATE TABLE IF NOT EXISTS thesis_events(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,thesis_id TEXT NOT NULL REFERENCES theses(id),event_type TEXT NOT NULL,state TEXT NOT NULL,details_json JSONB NOT NULL DEFAULT '{}'::jsonb,actor_id TEXT NOT NULL,occurred_at TIMESTAMPTZ NOT NULL)""")
    for table in TABLES:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'DROP POLICY IF EXISTS {table}_tenant_isolation ON "{table}"')
        op.execute(f"CREATE POLICY {table}_tenant_isolation ON \"{table}\" USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))")
def downgrade():
    for table in reversed(TABLES):op.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE')
