"""Captação/admissões: campanhas, leads, processo seletivo, ranking e reserva de vaga."""
from alembic import op
revision="0029_admissions_funnel"
down_revision="0028_government_education_operations"
branch_labels=None
depends_on=None
TABLES=("admission_campaigns","admission_leads","admission_processes","admission_assessments","admission_applications","admission_assessment_results","admission_vacancy_reservations")
def upgrade():
    op.execute("""CREATE TABLE IF NOT EXISTS admission_campaigns(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,program_id TEXT REFERENCES programs(id),academic_year_id TEXT REFERENCES academic_years(id),starts_on DATE NOT NULL,ends_on DATE,channels_json JSONB NOT NULL DEFAULT '[]'::jsonb,budget NUMERIC,state TEXT NOT NULL DEFAULT 'draft',created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,UNIQUE(tenant_id,code))""")
    op.execute("""CREATE TABLE IF NOT EXISTS admission_leads(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,campaign_id TEXT REFERENCES admission_campaigns(id),person_id TEXT REFERENCES people(id),full_name TEXT NOT NULL,email TEXT,phone TEXT,desired_program_id TEXT REFERENCES programs(id),desired_academic_year_id TEXT REFERENCES academic_years(id),source TEXT,external_ref TEXT,consent_at TIMESTAMPTZ,state TEXT NOT NULL DEFAULT 'new',owner_user_id TEXT,notes TEXT,converted_candidate_id TEXT REFERENCES admission_candidates(id),created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,UNIQUE(tenant_id,source,external_ref))""")
    op.execute("""CREATE TABLE IF NOT EXISTS admission_processes(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,program_id TEXT NOT NULL REFERENCES programs(id),academic_year_id TEXT NOT NULL REFERENCES academic_years(id),applications_open_at TIMESTAMPTZ,applications_close_at TIMESTAMPTZ,seats INTEGER,ranking_method TEXT NOT NULL DEFAULT 'weighted_sum',state TEXT NOT NULL DEFAULT 'draft',created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,UNIQUE(tenant_id,code))""")
    op.execute("""CREATE TABLE IF NOT EXISTS admission_assessments(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,process_id TEXT NOT NULL REFERENCES admission_processes(id),code TEXT NOT NULL,name TEXT NOT NULL,assessment_type TEXT NOT NULL,weight NUMERIC NOT NULL DEFAULT 1,max_score NUMERIC NOT NULL DEFAULT 100,scheduled_at TIMESTAMPTZ,state TEXT NOT NULL DEFAULT 'active',created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,UNIQUE(tenant_id,process_id,code))""")
    op.execute("""CREATE TABLE IF NOT EXISTS admission_applications(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,process_id TEXT NOT NULL REFERENCES admission_processes(id),candidate_id TEXT NOT NULL REFERENCES admission_candidates(id),application_number TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'applied',final_score NUMERIC,rank_position INTEGER,applied_at TIMESTAMPTZ NOT NULL,selected_at TIMESTAMPTZ,rejected_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL,UNIQUE(tenant_id,process_id,candidate_id),UNIQUE(tenant_id,application_number))""")
    op.execute("""CREATE TABLE IF NOT EXISTS admission_assessment_results(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,application_id TEXT NOT NULL REFERENCES admission_applications(id),assessment_id TEXT NOT NULL REFERENCES admission_assessments(id),score NUMERIC NOT NULL,outcome TEXT,notes TEXT,version INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL,UNIQUE(tenant_id,application_id,assessment_id))""")
    op.execute("""CREATE TABLE IF NOT EXISTS admission_vacancy_reservations(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,application_id TEXT NOT NULL REFERENCES admission_applications(id),candidate_id TEXT NOT NULL REFERENCES admission_candidates(id),class_group_id TEXT NOT NULL REFERENCES class_groups(id),expires_at TIMESTAMPTZ NOT NULL,state TEXT NOT NULL DEFAULT 'reserved',consumed_enrollment_id TEXT REFERENCES enrollments(id),reason TEXT,created_by TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL,updated_at TIMESTAMPTZ NOT NULL)""")
    op.execute("CREATE INDEX IF NOT EXISTS ix_admission_leads_state ON admission_leads(tenant_id,state,created_at)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_admission_applications_process ON admission_applications(tenant_id,process_id,state,rank_position)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_admission_reservations_capacity ON admission_vacancy_reservations(tenant_id,class_group_id,state,expires_at)")
    for table in TABLES:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY');op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY');op.execute(f'DROP POLICY IF EXISTS {table}_tenant_isolation ON "{table}"');op.execute(f"CREATE POLICY {table}_tenant_isolation ON \"{table}\" USING (tenant_id = current_setting('app.tenant_id', true)) WITH CHECK (tenant_id = current_setting('app.tenant_id', true))")
def downgrade():
    for table in reversed(TABLES):op.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE')
