fn main() {
    use std::env;
    use std::fs;
    use std::path::{Path, PathBuf};

    fn emit_agent(output: &mut String, name: &str, path: &Path) {
        if path.is_file() {
            let absolute = path.canonicalize().expect("canonicalize embedded PIGE360 agent");
            output.push_str(&format!("pub static {name}: &[u8] = include_bytes!(r#\"{}\"#);\n", absolute.display()));
        } else {
            output.push_str(&format!("pub static {name}: &[u8] = &[];\n"));
        }
    }

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let embedded = manifest.join("embedded");
    println!("cargo:rerun-if-changed={}", embedded.display());
    let mut output = String::from("// Generated by build.rs.\n");
    emit_agent(&mut output, "AGENT_LINUX_AMD64", &embedded.join("pige360-deploy-agent-linux-amd64"));
    fs::write(PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("pige360_embedded_agents.rs"), output)
        .expect("write embedded PIGE360 agents");

    #[cfg(feature = "desktop")]
    tauri_build::build();
}
