FROM python:3.13.5-slim-bookworm AS base
ARG VERSION=1.0.0-alpha.1
LABEL org.opencontainers.image.title="pige360-base-python" \
      org.opencontainers.image.version="$VERSION" \
      org.opencontainers.image.source="local-workspace" \
      org.opencontainers.image.licenses="Proprietary"
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_DISABLE_PIP_VERSION_CHECK=1
RUN groupadd --system --gid 10001 pige360 && useradd --system --uid 10001 --gid pige360 --home /opt/pige360 pige360 \
 && apt-get update && apt-get install -y --no-install-recommends ca-certificates curl tini libpq5 \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/pige360
USER 10001:10001
ENTRYPOINT ["/usr/bin/tini","--"]
