#!/usr/bin/env bash
set -euo pipefail
APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
set -a
[[ -f "$APP_DIR/.env" ]] && source "$APP_DIR/.env"
set +a

RESPECT_CLOUDPANEL_PORT="${PIGE360_DEPLOYER_RESPECT_CLOUDPANEL_PORT:-true}"
WEB_PORT="${PIGE360_DEPLOYER_WEB_PORT:-61002}"
if [[ "$RESPECT_CLOUDPANEL_PORT" =~ ^(1|true|TRUE|yes|YES|sim|SIM|on|ON)$ ]] && [[ -n "${PORT:-}" ]]; then
  WEB_PORT="$PORT"
fi

cat <<PORTS
Portas configuradas:

API Headless:
  Host: ${PIGE360_DEPLOYER_API_HOST:-127.0.0.1}
  Porta: ${PIGE360_DEPLOYER_API_PORT:-61001}
  URL: http://${PIGE360_DEPLOYER_API_HOST:-127.0.0.1}:${PIGE360_DEPLOYER_API_PORT:-61001}

Web / Browser / WebPort:
  Host: ${PIGE360_DEPLOYER_WEB_HOST:-127.0.0.1}
  Porta: $WEB_PORT
  URL: http://${PIGE360_DEPLOYER_WEB_HOST:-127.0.0.1}:$WEB_PORT

Webhook:
  Habilitado: ${PIGE360_DEPLOYER_WEBHOOK_ENABLED:-false}
  Host: ${PIGE360_DEPLOYER_WEBHOOK_HOST:-127.0.0.1}
  Porta: ${PIGE360_DEPLOYER_WEBHOOK_PORT:-61003}
  URL: http://${PIGE360_DEPLOYER_WEBHOOK_HOST:-127.0.0.1}:${PIGE360_DEPLOYER_WEBHOOK_PORT:-61003}${PIGE360_DEPLOYER_WEBHOOK_BASE_PATH:-/webhooks}

WebSocket:
  Habilitado: ${PIGE360_DEPLOYER_WEBSOCKET_ENABLED:-false}
  Host: ${PIGE360_DEPLOYER_WEBSOCKET_HOST:-127.0.0.1}
  Porta: ${PIGE360_DEPLOYER_WEBSOCKET_PORT:-61004}
  URL: ws://${PIGE360_DEPLOYER_WEBSOCKET_HOST:-127.0.0.1}:${PIGE360_DEPLOYER_WEBSOCKET_PORT:-61004}${PIGE360_DEPLOYER_WEBSOCKET_PATH:-/ws}

Publicar todas as portas: ${PIGE360_DEPLOYER_PUBLISH_ALL_PORTS:-false}
Iniciar todas as portas: ${PIGE360_DEPLOYER_START_ALL_PORTS:-false}
Respeitar PORT do CloudPanel: ${PIGE360_DEPLOYER_RESPECT_CLOUDPANEL_PORT:-true}
PORTS
