#!/usr/bin/env bash
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PID_FILE="$APP_DIR/pige360-deployer.pid"
LOG_DIR="$APP_DIR/logs"
LOG_FILE="$LOG_DIR/pige360-deployer.log"
ENV_FILE="$APP_DIR/.env"

mkdir -p "$LOG_DIR" "$APP_DIR/data"

set -a
[[ -f "$ENV_FILE" ]] && source "$ENV_FILE"
set +a

bool_true() {
  case "${1:-}" in
    1|true|TRUE|yes|YES|sim|SIM|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

BIN_PATH="${PIGE360_DEPLOYER_BINARY:-$APP_DIR/bin/pige360_deployer}"
if [[ "$BIN_PATH" != /* ]]; then
  BIN_PATH="$APP_DIR/${BIN_PATH#./}"
fi

if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
  echo "PIGE360 Deployer já está em execução. PID: $(cat "$PID_FILE")"
  exit 0
fi

if [[ ! -x "$BIN_PATH" ]]; then
  echo "Binário não encontrado ou sem permissão de execução: $BIN_PATH"
  echo "Execute: chmod +x $APP_DIR/bin/pige360_deployer"
  exit 1
fi

PUBLISH_ALL_PORTS="${PIGE360_DEPLOYER_PUBLISH_ALL_PORTS:-false}"
START_ALL_PORTS="${PIGE360_DEPLOYER_START_ALL_PORTS:-false}"
RESPECT_CLOUDPANEL_PORT="${PIGE360_DEPLOYER_RESPECT_CLOUDPANEL_PORT:-true}"
PUBLIC_BIND_HOST="${PIGE360_DEPLOYER_PUBLIC_BIND_HOST:-0.0.0.0}"

if bool_true "$PUBLISH_ALL_PORTS"; then
  export PIGE360_DEPLOYER_API_HOST="${PIGE360_DEPLOYER_API_HOST:-$PUBLIC_BIND_HOST}"
  export PIGE360_DEPLOYER_WEB_HOST="${PIGE360_DEPLOYER_WEB_HOST:-$PUBLIC_BIND_HOST}"
  export PIGE360_DEPLOYER_WEBHOOK_HOST="${PIGE360_DEPLOYER_WEBHOOK_HOST:-$PUBLIC_BIND_HOST}"
  export PIGE360_DEPLOYER_WEBSOCKET_HOST="${PIGE360_DEPLOYER_WEBSOCKET_HOST:-$PUBLIC_BIND_HOST}"
  export PIGE360_DEPLOYER_API_ALLOW_PUBLIC_NETWORK="${PIGE360_DEPLOYER_API_ALLOW_PUBLIC_NETWORK:-true}"
  export PIGE360_DEPLOYER_API_CORS="${PIGE360_DEPLOYER_API_CORS:-true}"
  export PIGE360_DEPLOYER_WEB_BIND_LAN="${PIGE360_DEPLOYER_WEB_BIND_LAN:-true}"
  export PIGE360_DEPLOYER_WEBHOOK_ALLOW_LAN="${PIGE360_DEPLOYER_WEBHOOK_ALLOW_LAN:-true}"
  export PIGE360_DEPLOYER_WEBHOOK_ALLOW_EXTERNAL="${PIGE360_DEPLOYER_WEBHOOK_ALLOW_EXTERNAL:-true}"
  export PIGE360_DEPLOYER_WEBSOCKET_ALLOW_LAN="${PIGE360_DEPLOYER_WEBSOCKET_ALLOW_LAN:-true}"
  export PIGE360_DEPLOYER_WEBSOCKET_ALLOW_EXTERNAL="${PIGE360_DEPLOYER_WEBSOCKET_ALLOW_EXTERNAL:-true}"
fi

if bool_true "$START_ALL_PORTS"; then
  export PIGE360_DEPLOYER_WEBHOOK_ENABLED=true
  export PIGE360_DEPLOYER_WEBHOOK_AUTO_START=true
  export PIGE360_DEPLOYER_WEBSOCKET_ENABLED=true
  export PIGE360_DEPLOYER_WEBSOCKET_AUTO_START=true
  export PIGE360_DEPLOYER_SERVICES_AUTO_START=true
fi

export PIGE360_DEPLOYER_ENV_FILE="${PIGE360_DEPLOYER_ENV_FILE:-$ENV_FILE}"
export PIGE360_DEPLOYER_WEB_DIST_DIR="${PIGE360_DEPLOYER_WEB_DIST_DIR:-$APP_DIR/dist}"
export PIGE360_DEPLOYER_DATA_DIR="${PIGE360_DEPLOYER_DATA_DIR:-$APP_DIR/data}"
export PIGE360_DEPLOYER_LOGS_DIR="${PIGE360_DEPLOYER_LOGS_DIR:-$LOG_DIR}"
export PIGE360_DEPLOYER_API_HOST="${PIGE360_DEPLOYER_API_HOST:-127.0.0.1}"
export PIGE360_DEPLOYER_API_PORT="${PIGE360_DEPLOYER_API_PORT:-61001}"
export PIGE360_DEPLOYER_WEB_HOST="${PIGE360_DEPLOYER_WEB_HOST:-127.0.0.1}"

if bool_true "$RESPECT_CLOUDPANEL_PORT" && [[ -n "${PORT:-}" ]]; then
  export PIGE360_DEPLOYER_WEB_PORT="$PORT"
else
  export PIGE360_DEPLOYER_WEB_PORT="${PIGE360_DEPLOYER_WEB_PORT:-61002}"
fi

export PIGE360_DEPLOYER_WEB_ENABLED="${PIGE360_DEPLOYER_WEB_ENABLED:-true}"
export PIGE360_DEPLOYER_WEB_AUTO_START="${PIGE360_DEPLOYER_WEB_AUTO_START:-true}"
export PIGE360_DEPLOYER_SERVICES_AUTO_START="${PIGE360_DEPLOYER_SERVICES_AUTO_START:-true}"
export PIGE360_DEPLOYER_WEBHOOK_HOST="${PIGE360_DEPLOYER_WEBHOOK_HOST:-127.0.0.1}"
export PIGE360_DEPLOYER_WEBHOOK_PORT="${PIGE360_DEPLOYER_WEBHOOK_PORT:-61003}"
export PIGE360_DEPLOYER_WEBSOCKET_HOST="${PIGE360_DEPLOYER_WEBSOCKET_HOST:-127.0.0.1}"
export PIGE360_DEPLOYER_WEBSOCKET_PORT="${PIGE360_DEPLOYER_WEBSOCKET_PORT:-61004}"

ARGS=(
  --mode=headless-api
  --host "$PIGE360_DEPLOYER_API_HOST"
  --port "$PIGE360_DEPLOYER_API_PORT"
  --data-dir "$PIGE360_DEPLOYER_DATA_DIR"
  --start-web-proxy
  --start-services
)

if [[ "${PIGE360_DEPLOYER_WEBHOOK_ENABLED:-false}" == "true" ]]; then
  ARGS+=(--start-webhook)
fi

if [[ "${PIGE360_DEPLOYER_WEBSOCKET_ENABLED:-false}" == "true" ]]; then
  ARGS+=(--start-websocket)
fi

cd "$APP_DIR"
nohup "$BIN_PATH" "${ARGS[@]}" >> "$LOG_FILE" 2>&1 &

echo $! > "$PID_FILE"
echo "PIGE360 Deployer iniciado. PID: $(cat "$PID_FILE")"
echo "WebPort:  http://$PIGE360_DEPLOYER_WEB_HOST:$PIGE360_DEPLOYER_WEB_PORT"
echo "API:      http://$PIGE360_DEPLOYER_API_HOST:$PIGE360_DEPLOYER_API_PORT"
echo "Webhook:  http://$PIGE360_DEPLOYER_WEBHOOK_HOST:$PIGE360_DEPLOYER_WEBHOOK_PORT${PIGE360_DEPLOYER_WEBHOOK_BASE_PATH:-/webhooks} (${PIGE360_DEPLOYER_WEBHOOK_ENABLED:-false})"
echo "WebSocket: ws://$PIGE360_DEPLOYER_WEBSOCKET_HOST:$PIGE360_DEPLOYER_WEBSOCKET_PORT${PIGE360_DEPLOYER_WEBSOCKET_PATH:-/ws} (${PIGE360_DEPLOYER_WEBSOCKET_ENABLED:-false})"
echo "Logs:     $LOG_FILE"
