<script setup lang="ts">
import { computed,reactive,ref,watch } from "vue";
import type { Pige360SessionClient } from "@pige360/auth";
type Row=Record<string,any>;
const props=defineProps<{api:Pige360SessionClient;assignments:Row[];periods:Row[]}>();
const emit=defineEmits<{notice:[string];error:[string]}>();
const selectedAssignment=ref(""),selectedPeriod=ref(""),assessments=ref<Row[]>([]),detail=ref<Row|null>(null),results=ref<Row[]>([]),busy=ref(false);
const form=reactive({title:"",assessment_type:"exam",weight:"1",max_score:"10",due_on:""});
const gradeForm=reactive<Record<string,{score:string;feedback:string;version:number|null}>>({});
const assignment=computed(()=>props.assignments.find(x=>x.id===selectedAssignment.value));
const periods=computed(()=>props.periods.filter(x=>!assignment.value||x.academic_year_id===assignment.value.academic_year_id));
async function loadAssessments(){detail.value=null;results.value=[];if(!assignment.value||!selectedPeriod.value){assessments.value=[];return;}try{const a=assignment.value;const r=await props.api.request<Row>(`/pedagogy/assessments?academic_period_id=${selectedPeriod.value}&class_group_id=${a.class_group_id}&component_id=${a.component_id}`);assessments.value=r.items||[];}catch(e){emit('error',e instanceof Error?e.message:'Erro ao carregar avaliações');}}
async function createAssessment(){if(!assignment.value||!selectedPeriod.value)return;busy.value=true;try{const a=assignment.value;const created=await props.api.request<Row>("/pedagogy/assessments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({academic_period_id:selectedPeriod.value,class_group_id:a.class_group_id,component_id:a.component_id,title:form.title,assessment_type:form.assessment_type,weight:form.weight,max_score:form.max_score,due_on:form.due_on||null})});await props.api.request(`/pedagogy/assessments/${created.id}/publish`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expected_version:created.version,reason:"Avaliação publicada pelo professor"})});Object.assign(form,{title:"",assessment_type:"exam",weight:"1",max_score:"10",due_on:""});emit('notice','Avaliação criada e publicada.');await loadAssessments();}catch(e){emit('error',e instanceof Error?e.message:'Erro ao criar avaliação');}finally{busy.value=false;}}
async function openAssessment(row:Row){busy.value=true;try{const opened=await props.api.request<Row>(`/pedagogy/assessments/${row.id}`);detail.value=opened;for(const student of opened.roster||[]){const existing=(opened.grades||[]).find((g:Row)=>g.enrollment_id===student.enrollment_id);gradeForm[student.enrollment_id]={score:existing?.score==null?"":String(existing.score),feedback:existing?.feedback||"",version:existing?.version??null};}}catch(e){emit('error',e instanceof Error?e.message:'Erro ao abrir avaliação');}finally{busy.value=false;}}
async function saveGrades(){const current=detail.value;if(!current)return;busy.value=true;try{const grades=(current.roster||[]).map((student:Row)=>{const g=gradeForm[student.enrollment_id];return{enrollment_id:student.enrollment_id,score:g?.score===""?null:g?.score,status:g?.score===""?"missing":"graded",feedback:g?.feedback||null,expected_version:g?.version??null};});await props.api.request(`/pedagogy/assessments/${current.id}/grades`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Lançamento pelo diário do professor",grades})});emit('notice','Notas salvas com versionamento.');await openAssessment(current);}catch(e){emit('error',e instanceof Error?e.message:'Erro ao salvar notas');}finally{busy.value=false;}}
async function calculate(){if(!assignment.value||!selectedPeriod.value)return;busy.value=true;try{const a=assignment.value;const r=await props.api.request<Row>("/pedagogy/period-results/calculate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({academic_period_id:selectedPeriod.value,class_group_id:a.class_group_id,component_id:a.component_id})});results.value=r.items||[];emit('notice','Médias recalculadas pelas regras vigentes.');}catch(e){emit('error',e instanceof Error?e.message:'Erro ao calcular resultados');}finally{busy.value=false;}}
watch([selectedAssignment,selectedPeriod],()=>void loadAssessments());
</script>
<template><section class="panel grading"><div class="section-title"><div><h2>Avaliações e notas</h2><small>Notas versionadas, recuperação e fechamento pela coordenação</small></div></div><div class="cols"><label>Atribuição<select v-model="selectedAssignment"><option value="">Selecione</option><option v-for="a in assignments" :key="a.id" :value="a.id">{{a.class_group_name}} — {{a.component_name}}</option></select></label><label>Período<select v-model="selectedPeriod"><option value="">Selecione</option><option v-for="p in periods" :key="p.id" :value="p.id">{{p.name}}</option></select></label></div><form v-if="selectedAssignment&&selectedPeriod" class="grade-create" @submit.prevent="createAssessment"><input v-model="form.title" placeholder="Título da avaliação" required><select v-model="form.assessment_type"><option value="exam">Prova</option><option value="work">Trabalho</option><option value="project">Projeto</option><option value="formative">Formativa</option></select><input v-model="form.weight" type="number" step="0.01" min="0.01" title="Peso"><input v-model="form.max_score" type="number" step="0.01" min="0.01" title="Nota máxima"><input v-model="form.due_on" type="date"><button :disabled="busy">Criar e publicar</button></form><div class="assessment-list"><button v-for="a in assessments" :key="a.id" class="assessment-card" @click="openAssessment(a)"><div><strong>{{a.title}}</strong><small>{{a.assessment_type}} · peso {{a.weight}} · máx. {{a.max_score}}</small></div><span>{{a.state}}</span></button><p v-if="selectedPeriod&&!assessments.length" class="empty">Nenhuma avaliação neste período.</p></div><div v-if="detail" class="grade-sheet"><div class="section-title"><h3>{{detail.title}}</h3><span>{{detail.state}}</span></div><div class="grade-row head"><span>Aluno</span><span>Nota / {{detail.max_score}}</span><span>Feedback</span></div><div v-for="s in detail.roster" :key="s.enrollment_id" class="grade-row"><span><strong>{{s.social_name||s.full_name}}</strong><small>{{s.registration_number}}</small></span><input v-model="gradeForm[s.enrollment_id].score" type="number" step="0.01" min="0" :max="detail.max_score"><input v-model="gradeForm[s.enrollment_id].feedback" placeholder="Feedback"></div><div class="actions"><button class="secondary" :disabled="busy" @click="calculate">Calcular médias</button><button :disabled="busy" @click="saveGrades">Salvar notas</button></div></div><div v-if="results.length" class="result-grid"><article v-for="r in results" :key="r.id"><strong>{{r.final_score}}</strong><span>{{r.outcome}}</span><small>freq. {{r.attendance_percentage}}%</small></article></div></section></template>
