<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from "vue";
import type { Pige360SessionClient } from "@pige360/auth";
type Row=Record<string,any>;
const props=defineProps<{api:Pige360SessionClient}>();const emit=defineEmits<{error:[string];notice:[string]}>();
const students=ref<Row[]>([]),components=ref<Row[]>([]),selectedStudent=ref(""),integralization=ref<Row>({enrollments:[]}),daily=ref<Row[]>([]),internships=ref<Row[]>([]),activities=ref<Row[]>([]),theses=ref<Row[]>([]),prerequisites=ref<Row[]>([]),busy=ref(false);
const internshipForm=reactive({enrollment_id:"",organization_name:"",supervisor_name:"",starts_on:"",ends_on:"",required_hours:"0",notes:""});
const activityForm=reactive({enrollment_id:"",category:"extensão",title:"",requested_hours:""});
const thesisForm=reactive({enrollment_id:"",title:"",abstract:""});
const prereqForm=reactive({component_id:"",prerequisite_component_id:"",minimum_final_score:""});
const enrollments=computed(()=>integralization.value.enrollments||[]);
function msg(e:unknown){return e instanceof Error?e.message:"Erro na progressão acadêmica";}
async function boot(){try{const [s,c,p]=await Promise.all([props.api.request<Row>("/students?limit=500"),props.api.request<Row>("/curriculum-components"),props.api.request<Row>("/academic/component-prerequisites")]);students.value=s.items||[];components.value=c.items||[];prerequisites.value=p.items||[];}catch(e){emit("error",msg(e));}}
async function loadStudent(){integralization.value={enrollments:[]};daily.value=[];internships.value=[];activities.value=[];theses.value=[];if(!selectedStudent.value)return;busy.value=true;try{const [i,d,stages,acts,tcc]=await Promise.all([props.api.request<Row>(`/academic/students/${selectedStudent.value}/integralization`),props.api.request<Row>(`/academic/early-childhood/students/${selectedStudent.value}/daily-records`).catch(()=>({items:[]})),props.api.request<Row>("/academic/internships"),props.api.request<Row>("/academic/complementary-activities"),props.api.request<Row>("/academic/theses")]);integralization.value=i;daily.value=d.items||[];const ids=new Set((i.enrollments||[]).map((x:Row)=>x.enrollment.id));internships.value=(stages.items||[]).filter((x:Row)=>ids.has(x.enrollment_id));activities.value=(acts.items||[]).filter((x:Row)=>ids.has(x.enrollment_id));theses.value=(tcc.items||[]).filter((x:Row)=>ids.has(x.enrollment_id));const first=i.enrollments?.[0]?.enrollment?.id||"";internshipForm.enrollment_id=first;activityForm.enrollment_id=first;thesisForm.enrollment_id=first;}catch(e){emit("error",msg(e));}finally{busy.value=false;}}
async function createPrerequisite(){try{await props.api.request("/academic/component-prerequisites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({component_id:prereqForm.component_id,prerequisite_component_id:prereqForm.prerequisite_component_id,minimum_final_score:prereqForm.minimum_final_score||null})});prerequisites.value=(await props.api.request<Row>("/academic/component-prerequisites")).items||[];emit("notice","Pré-requisito curricular salvo.");}catch(e){emit("error",msg(e));}}
async function createInternship(){try{await props.api.request("/academic/internships",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...internshipForm,ends_on:internshipForm.ends_on||null,supervisor_name:internshipForm.supervisor_name||null,required_hours:internshipForm.required_hours||"0"})});emit("notice","Estágio cadastrado.");await loadStudent();}catch(e){emit("error",msg(e));}}
async function stageInternship(row:Row,state:string){try{await props.api.request(`/academic/internships/${row.id}/state`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({state,expected_version:row.version,reason:`Alteração administrativa para ${state}`})});emit("notice","Estado do estágio atualizado.");await loadStudent();}catch(e){emit("error",msg(e));}}
async function createActivity(){try{await props.api.request("/academic/complementary-activities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(activityForm)});emit("notice","Atividade complementar registrada.");await loadStudent();}catch(e){emit("error",msg(e));}}
async function decideActivity(row:Row,state:"approved"|"rejected"){try{const hours=state==="approved"?String(row.requested_hours):"0";await props.api.request(`/academic/complementary-activities/${row.id}/decision`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({state,approved_hours:hours,notes:state==="approved"?"Atividade homologada pela coordenação":"Atividade não homologada pela coordenação"})});emit("notice","Atividade analisada.");await loadStudent();}catch(e){emit("error",msg(e));}}
async function createThesis(){try{await props.api.request("/academic/theses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...thesisForm,abstract:thesisForm.abstract||null})});emit("notice","TCC cadastrado.");await loadStudent();}catch(e){emit("error",msg(e));}}
async function stageThesis(row:Row,state:string){const payload:Row={state,expected_version:row.version,reason:`Alteração acadêmica para ${state}`};if(state==="defended"){payload.defense_at=new Date().toISOString();}try{await props.api.request(`/academic/theses/${row.id}/state`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});emit("notice","Estado do TCC atualizado.");await loadStudent();}catch(e){emit("error",msg(e));}}
function componentName(id:string){return components.value.find(x=>x.id===id)?.name||id;}
watch(selectedStudent,()=>void loadStudent());onMounted(boot);
</script>
<template>
<div class="academic-progress">
  <section class="panel"><div class="panel-title"><div><h2>Progressão acadêmica</h2><p>Educação Infantil, pré-requisitos, estágio, atividades complementares, TCC e integralização.</p></div><label>Aluno<select v-model="selectedStudent"><option value="">Selecione</option><option v-for="s in students" :key="s.id" :value="s.id">{{s.full_name}} — {{s.registration_number}}</option></select></label></div></section>
  <section class="grid-2 forms"><form class="panel" @submit.prevent="createPrerequisite"><h2>Pré-requisito curricular</h2><label>Componente<select v-model="prereqForm.component_id" required><option value="">Selecione</option><option v-for="c in components" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>Pré-requisito<select v-model="prereqForm.prerequisite_component_id" required><option value="">Selecione</option><option v-for="c in components" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>Nota mínima<input v-model="prereqForm.minimum_final_score" type="number" min="0" step="0.01"></label><button class="primary">Salvar regra</button></form><div class="panel"><h2>Regras cadastradas</h2><div class="notice-list"><article v-for="p in prerequisites.slice(0,20)" :key="p.id"><strong>{{componentName(p.component_id)}}</strong><p>Exige {{p.prerequisite_name||componentName(p.prerequisite_component_id)}}<template v-if="p.minimum_final_score"> · nota mínima {{p.minimum_final_score}}</template></p></article><p v-if="!prerequisites.length" class="empty">Sem pré-requisitos configurados.</p></div></div></section>
  <template v-if="selectedStudent">
    <section v-if="daily.length" class="panel"><div class="panel-title"><h2>Agenda da Educação Infantil</h2><span>{{daily.length}} registros</span></div><table><thead><tr><th>Data</th><th>Humor</th><th>Desenvolvimento</th><th>Versão</th></tr></thead><tbody><tr v-for="r in daily.slice(0,30)" :key="r.id"><td>{{r.record_date}}</td><td>{{r.mood||'—'}}</td><td>{{r.development_notes||'—'}}</td><td>v{{r.version}}</td></tr></tbody></table></section>
    <section v-for="en in enrollments" :key="en.enrollment.id" class="panel"><div class="panel-title"><div><h2>{{en.enrollment.program_name}} · {{en.enrollment.curriculum_name}}</h2><p>{{en.curriculum.components_completed}}/{{en.curriculum.components_total}} componentes · {{en.curriculum.workload_hours_completed}}/{{en.curriculum.workload_hours_total}}h</p></div><strong>{{en.curriculum.completion_percentage}}%</strong></div><table><thead><tr><th>Componente</th><th>Carga</th><th>Créditos</th><th>Integralizado</th></tr></thead><tbody><tr v-for="c in en.components" :key="c.id"><td>{{c.name}}</td><td>{{c.workload_hours}}h</td><td>{{c.credits||'—'}}</td><td><span class="pill" :class="c.completed?'ok':'warn'">{{c.completed?'Sim':'Pendente'}}</span></td></tr></tbody></table></section>
    <section class="grid-2 forms"><form class="panel" @submit.prevent="createInternship"><h2>Novo estágio</h2><label>Matrícula<select v-model="internshipForm.enrollment_id" required><option v-for="e in enrollments" :key="e.enrollment.id" :value="e.enrollment.id">{{e.enrollment.program_name}}</option></select></label><label>Concedente<input v-model="internshipForm.organization_name" required></label><label>Supervisor<input v-model="internshipForm.supervisor_name"></label><div class="cols"><label>Início<input v-model="internshipForm.starts_on" type="date" required></label><label>Fim<input v-model="internshipForm.ends_on" type="date"></label></div><label>Carga obrigatória<input v-model="internshipForm.required_hours" type="number" min="0" step="0.5"></label><button class="primary">Cadastrar estágio</button></form><div class="panel"><h2>Estágios</h2><div class="notice-list"><article v-for="i in internships" :key="i.id"><strong>{{i.organization_name}}</strong><p>{{i.completed_hours}}/{{i.required_hours}}h · {{i.state}}</p><div class="row-actions"><button v-if="i.state==='draft'" class="small" @click="stageInternship(i,'approved')">Aprovar</button><button v-if="i.state==='approved'" class="small" @click="stageInternship(i,'in_progress')">Iniciar</button><button v-if="i.state==='in_progress'" class="small" @click="stageInternship(i,'completed')">Concluir</button></div></article></div></div></section>
    <section class="grid-2 forms"><form class="panel" @submit.prevent="createActivity"><h2>Atividade complementar</h2><label>Matrícula<select v-model="activityForm.enrollment_id" required><option v-for="e in enrollments" :key="e.enrollment.id" :value="e.enrollment.id">{{e.enrollment.program_name}}</option></select></label><label>Categoria<input v-model="activityForm.category" required></label><label>Título<input v-model="activityForm.title" required></label><label>Horas solicitadas<input v-model="activityForm.requested_hours" type="number" min="0.5" step="0.5" required></label><button class="primary">Registrar atividade</button></form><div class="panel"><h2>Atividades</h2><div class="notice-list"><article v-for="a in activities" :key="a.id"><strong>{{a.title}}</strong><p>{{a.category}} · {{a.requested_hours}}h · {{a.state}}</p><div v-if="a.state==='submitted'||a.state==='additional_information_required'" class="row-actions"><button class="small" @click="decideActivity(a,'approved')">Homologar</button><button class="small" @click="decideActivity(a,'rejected')">Rejeitar</button></div></article></div></div></section>
    <section class="grid-2 forms"><form class="panel" @submit.prevent="createThesis"><h2>Trabalho de conclusão</h2><label>Matrícula<select v-model="thesisForm.enrollment_id" required><option v-for="e in enrollments" :key="e.enrollment.id" :value="e.enrollment.id">{{e.enrollment.program_name}}</option></select></label><label>Título<input v-model="thesisForm.title" required></label><label>Resumo<textarea v-model="thesisForm.abstract" rows="4"></textarea></label><button class="primary">Cadastrar TCC</button></form><div class="panel"><h2>TCCs</h2><div class="notice-list"><article v-for="t in theses" :key="t.id"><strong>{{t.title}}</strong><p>{{t.state}}<template v-if="t.grade"> · nota {{t.grade}}</template></p><div class="row-actions"><button v-if="t.state==='proposal'" class="small" @click="stageThesis(t,'approved')">Aprovar</button><button v-if="t.state==='approved'" class="small" @click="stageThesis(t,'in_progress')">Iniciar</button><button v-if="t.state==='in_progress'" class="small" @click="stageThesis(t,'submitted')">Submeter</button><button v-if="t.state==='submitted'" class="small" @click="stageThesis(t,'defended')">Registrar defesa</button><button v-if="t.state==='defended'" class="small" @click="stageThesis(t,'passed')">Aprovar TCC</button></div></article></div></div></section>
  </template>
</div>
</template>
