<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import type { Pige360SessionClient } from "@pige360/auth";
type Row=Record<string,any>;
const props=defineProps<{api:Pige360SessionClient}>();const emit=defineEmits<{error:[string];notice:[string]}>();
const dashboard=ref<Row>({}),notices=ref<Row[]>([]),processing=ref<Row[]>([]),requests=ref<Row[]>([]),retention=ref<Row[]>([]),holds=ref<Row[]>([]),busy=ref(false);
const noticeForm=reactive({code:"PRIVACY-GENERAL",title:"Aviso de Privacidade",content:"",effective_from:new Date().toISOString().slice(0,10),effective_until:""});
const processingForm=reactive({code:"",name:"",purpose:"",legal_basis:"",privacy_notice_code:"",data_categories:"",data_subjects:"",recipients:"",retention_rule:"",security_measures:"tenant_isolation, encryption, audit",owner_department:""});
const retentionForm=reactive({data_category:"",purpose_code:"",retention_days:1825,disposition:"anonymize",legal_basis:"",starts_on:new Date().toISOString().slice(0,10)});
const holdForm=reactive({person_id:"",aggregate_type:"",aggregate_id:"",reason:""});
function msg(e:unknown){return e instanceof Error?e.message:"Erro de compliance";}function list(v:string){return v.split(",").map(x=>x.trim()).filter(Boolean);}
async function load(){busy.value=true;try{const [d,n,p,r,ret,h]=await Promise.all([props.api.request<Row>("/compliance/dashboard"),props.api.request<Row>("/compliance/privacy-notices"),props.api.request<Row>("/compliance/processing-activities"),props.api.request<Row>("/compliance/data-subject-requests"),props.api.request<Row>("/compliance/retention-policies"),props.api.request<Row>("/compliance/legal-holds")]);dashboard.value=d;notices.value=n.items||[];processing.value=p.items||[];requests.value=r.items||[];retention.value=ret.items||[];holds.value=h.items||[];}catch(e){emit("error",msg(e));}finally{busy.value=false;}}
async function createNotice(){try{await props.api.request("/compliance/privacy-notices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...noticeForm,effective_until:noticeForm.effective_until||null})});emit("notice","Nova versão do aviso criada.");await load();}catch(e){emit("error",msg(e));}}
async function publish(n:Row){try{await props.api.request(`/compliance/privacy-notices/${n.id}/publish`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Publicação aprovada no painel de compliance"})});emit("notice","Aviso de privacidade publicado.");await load();}catch(e){emit("error",msg(e));}}
async function createProcessing(){try{await props.api.request("/compliance/processing-activities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:processingForm.code,name:processingForm.name,purpose:processingForm.purpose,legal_basis:processingForm.legal_basis,privacy_notice_code:processingForm.privacy_notice_code||null,data_categories:list(processingForm.data_categories),data_subjects:list(processingForm.data_subjects),recipients:list(processingForm.recipients),retention_rule:processingForm.retention_rule||null,security_measures:list(processingForm.security_measures),owner_department:processingForm.owner_department||null,international_transfer:false})});emit("notice","Atividade de tratamento registrada.");await load();}catch(e){emit("error",msg(e));}}
async function stateRequest(row:Row,state:string){try{await props.api.request(`/compliance/data-subject-requests/${row.id}/state`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({state,reason:`Tratamento administrativo: ${state}`})});emit("notice","Solicitação LGPD atualizada.");await load();}catch(e){emit("error",msg(e));}}
async function exportRequest(row:Row){try{const result=await props.api.request<Row>(`/compliance/data-subject-requests/${row.id}/export`,{method:"POST"});emit("notice",`Exportação gerada · SHA-256 ${result.sha256.slice(0,16)}…`);await load();}catch(e){emit("error",msg(e));}}
async function anonymize(row:Row){if(!confirm("Confirmar anonimização controlada? A operação preserva fatos históricos e pseudonimiza o cadastro pessoal."))return;try{await props.api.request(`/compliance/data-subject-requests/${row.id}/anonymize`,{method:"POST"});emit("notice","Anonimização executada e auditada.");await load();}catch(e){emit("error",msg(e));}}
async function createRetention(){try{await props.api.request("/compliance/retention-policies",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...retentionForm,purpose_code:retentionForm.purpose_code||null})});emit("notice","Política de retenção criada.");await load();}catch(e){emit("error",msg(e));}}
async function createHold(){try{await props.api.request("/compliance/legal-holds",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({person_id:holdForm.person_id||null,aggregate_type:holdForm.aggregate_type||null,aggregate_id:holdForm.aggregate_id||null,reason:holdForm.reason})});emit("notice","Legal hold criado.");await load();}catch(e){emit("error",msg(e));}}
async function releaseHold(row:Row){try{await props.api.request(`/compliance/legal-holds/${row.id}/release`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Motivo de preservação encerrado"})});emit("notice","Legal hold liberado.");await load();}catch(e){emit("error",msg(e));}}
onMounted(load);
</script>
<template>
<div class="compliance-panel">
  <section class="metrics"><article><span>Solicitações abertas</span><strong>{{dashboard.open_data_subject_requests||0}}</strong><small>direitos do titular</small></article><article><span>Consentimentos ativos</span><strong>{{dashboard.active_consents||0}}</strong><small>vigentes</small></article><article><span>Legal holds</span><strong>{{dashboard.active_legal_holds||0}}</strong><small>preservações ativas</small></article><article><span>Tratamentos</span><strong>{{dashboard.processing_activities||0}}</strong><small>inventariados</small></article></section>
  <section class="grid-2 forms"><form class="panel" @submit.prevent="createNotice"><h2>Aviso de privacidade</h2><div class="cols"><label>Código<input v-model="noticeForm.code" required></label><label>Título<input v-model="noticeForm.title" required></label></div><label>Conteúdo<textarea v-model="noticeForm.content" rows="8" minlength="20" required></textarea></label><div class="cols"><label>Vigência inicial<input v-model="noticeForm.effective_from" type="date" required></label><label>Vigência final<input v-model="noticeForm.effective_until" type="date"></label></div><button class="primary">Criar versão</button></form><div class="panel"><h2>Versões</h2><div class="notice-list"><article v-for="n in notices" :key="n.id"><strong>{{n.title}} · v{{n.version}}</strong><p>{{n.code}} · {{n.effective_from}} · {{n.state}}</p><small><code>{{n.sha256}}</code></small><button v-if="n.state==='draft'" class="small" @click="publish(n)">Publicar</button></article></div></div></section>
  <section class="grid-2 forms"><form class="panel" @submit.prevent="createProcessing"><h2>Inventário de tratamento</h2><div class="cols"><label>Código<input v-model="processingForm.code" required></label><label>Nome<input v-model="processingForm.name" required></label></div><label>Finalidade<textarea v-model="processingForm.purpose" rows="3" required></textarea></label><label>Base legal<input v-model="processingForm.legal_basis" required></label><label v-if="processingForm.legal_basis.toLowerCase()==='consent'">Código do aviso de privacidade<input v-model="processingForm.privacy_notice_code" placeholder="PRIVACY-GENERAL" required></label><label>Categorias de dados<input v-model="processingForm.data_categories" placeholder="identificação, acadêmico, financeiro"></label><label>Titulares<input v-model="processingForm.data_subjects" placeholder="aluno, responsável, colaborador"></label><label>Destinatários<input v-model="processingForm.recipients"></label><label>Regra de retenção<input v-model="processingForm.retention_rule"></label><label>Medidas de segurança<input v-model="processingForm.security_measures"></label><button class="primary">Registrar tratamento</button></form><div class="panel"><h2>Atividades de tratamento</h2><div class="notice-list"><article v-for="p in processing" :key="p.id"><strong>{{p.name}} · v{{p.version}}</strong><p>{{p.purpose}}</p><small>{{p.legal_basis}} · {{(p.data_categories||[]).join(', ')}}</small></article></div></div></section>
  <section class="panel"><div class="panel-title"><h2>Solicitações dos titulares</h2><span>{{requests.length}}</span></div><table><thead><tr><th>Protocolo</th><th>Tipo</th><th>Titular</th><th>Estado</th><th>Prazo</th><th>Ações</th></tr></thead><tbody><tr v-for="r in requests" :key="r.id"><td>{{r.protocol}}</td><td>{{r.request_type}}</td><td><code>{{r.subject_person_id}}</code></td><td><span class="pill">{{r.state}}</span></td><td>{{r.due_at}}</td><td class="row-actions"><button v-if="r.state==='submitted'" class="small" @click="stateRequest(r,'under_review')">Analisar</button><button v-if="r.state==='under_review'" class="small" @click="stateRequest(r,'approved')">Aprovar</button><button v-if="['under_review','approved'].includes(r.state)&&['access','export'].includes(r.request_type)" class="small" @click="exportRequest(r)">Gerar exportação</button><button v-if="r.request_type==='anonymization'&&r.state==='approved'" class="small danger" @click="anonymize(r)">Anonimizar</button><button v-if="r.state==='approved'&&r.request_type!=='anonymization'" class="small" @click="stateRequest(r,'fulfilled')">Concluir</button></td></tr></tbody></table></section>
  <section class="grid-2 forms"><form class="panel" @submit.prevent="createRetention"><h2>Política de retenção</h2><label>Categoria<input v-model="retentionForm.data_category" required></label><label>Finalidade<input v-model="retentionForm.purpose_code"></label><div class="cols"><label>Dias<input v-model.number="retentionForm.retention_days" type="number" min="1" required></label><label>Destino<select v-model="retentionForm.disposition"><option value="archive">Arquivar</option><option value="anonymize">Anonimizar</option><option value="delete">Eliminar quando juridicamente permitido</option></select></label></div><label>Base legal<input v-model="retentionForm.legal_basis" required></label><label>Início<input v-model="retentionForm.starts_on" type="date" required></label><button class="primary">Criar política</button></form><div class="panel"><h2>Políticas vigentes</h2><div class="notice-list"><article v-for="r in retention" :key="r.id"><strong>{{r.data_category}} · v{{r.version}}</strong><p>{{r.retention_days}} dias → {{r.disposition}}</p><small>{{r.legal_basis}}</small></article></div></div></section>
  <section class="grid-2 forms"><form class="panel" @submit.prevent="createHold"><h2>Legal hold</h2><label>Person ID<input v-model="holdForm.person_id" placeholder="Titular"></label><label>Agregado<input v-model="holdForm.aggregate_type" placeholder="contract, fiscal_document…"></label><label>Aggregate ID<input v-model="holdForm.aggregate_id"></label><label>Motivo<textarea v-model="holdForm.reason" rows="3" required></textarea></label><button class="primary">Preservar</button></form><div class="panel"><h2>Preservações</h2><div class="notice-list"><article v-for="h in holds" :key="h.id"><strong>{{h.person_id||`${h.aggregate_type}/${h.aggregate_id}`}}</strong><p>{{h.reason}}</p><small>{{h.state}} · {{h.starts_at}}</small><button v-if="h.state==='active'" class="small" @click="releaseHold(h)">Liberar</button></article></div></div></section>
</div>
</template>
