<script setup lang="ts">
import {onMounted,reactive,ref} from "vue";
import type {Pige360SessionClient} from "@pige360/auth";
type Row=Record<string,any>;
const props=defineProps<{api:Pige360SessionClient}>();const emit=defineEmits<{error:[string];notice:[string]}>();
const busy=ref(false),layouts=ref<Row[]>([]),validations=ref<Row[]>([]),imports=ref<Row[]>([]),exports=ref<Row[]>([]),transmissions=ref<Row[]>([]),connections=ref<Row[]>([]),issues=ref<Row[]>([]);const importFile=ref<File|null>(null);
const today=new Date().toISOString().slice(0,10);
const layoutForm=reactive({authority:"INEP",layout_code:"EDUCACENSO-MATRICULA",version:"2026.1",effective_from:today,fields_json:'[{"name":"student_code","required":true,"max_length":20},{"name":"enrollment_state","required":true,"enum":["ACTIVE","TRANSFERRED"]}]'});
const runForm=reactive({layout_id:"",reference_period:"2026",records_json:'[{"student_code":"ABC123","enrollment_state":"ACTIVE"}]'});
const importForm=reactive({layout_id:"",reference_period:"2026"});
function msg(e:unknown){return e instanceof Error?e.message:"Erro na integração educacional";}function parseRecords(v:string){const x=JSON.parse(v);if(!Array.isArray(x))throw new Error("Informe uma lista JSON de registros.");return x;}function parseFields(v:string){const x=JSON.parse(v);if(!Array.isArray(x)||!x.length)throw new Error("Informe ao menos um campo no layout.");return x;}
async function load(){busy.value=true;try{const [l,v,i,e,t,c]=await Promise.all([props.api.request<Row>("/government-education/layouts"),props.api.request<Row>("/government-education/validations"),props.api.request<Row>("/government-education/imports"),props.api.request<Row>("/government-education/exports"),props.api.request<Row>("/government-education/transmissions"),props.api.request<Row>("/integration-connections")]);layouts.value=l.items||[];validations.value=v.items||[];imports.value=i.items||[];exports.value=e.items||[];transmissions.value=t.items||[];connections.value=(c.items||[]).filter((x:Row)=>(x.capabilities||[]).includes("government_submission"));if(!runForm.layout_id&&layouts.value[0])runForm.layout_id=layouts.value[0].id;if(!importForm.layout_id&&layouts.value[0])importForm.layout_id=layouts.value[0].id;}catch(e){emit("error",msg(e));}finally{busy.value=false;}}
async function createLayout(){try{await props.api.request("/government-education/layouts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({authority:layoutForm.authority,layout_code:layoutForm.layout_code,version:layoutForm.version,effective_from:layoutForm.effective_from,layout_schema:{format:"csv",fields:parseFields(layoutForm.fields_json)}})});emit("notice","Layout governamental versionado registrado.");await load();}catch(e){emit("error",msg(e));}}
async function validate(){try{const r=await props.api.request<Row>("/government-education/validations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({layout_id:runForm.layout_id,reference_period:runForm.reference_period,direction:"export",records:parseRecords(runForm.records_json)})});issues.value=r.issues||[];emit("notice",r.state==="valid"?"Validação concluída sem inconsistências.":`Validação encontrou ${r.error_count} erro(s).`);await load();}catch(e){emit("error",msg(e));}}
async function generateExport(){try{const r=await props.api.request<Row>("/government-education/exports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({layout_id:runForm.layout_id,reference_period:runForm.reference_period,records:parseRecords(runForm.records_json)})});emit("notice",`Exportação gerada · SHA-256 ${String(r.sha256).slice(0,16)}…`);await load();}catch(e){emit("error",msg(e));}}
async function uploadImport(){if(!importFile.value)return;try{const body=new FormData();body.append("file",importFile.value);const q=new URLSearchParams({layout_id:importForm.layout_id,reference_period:importForm.reference_period});const r=await props.api.request<Row>(`/government-education/imports?${q}`,{method:"POST",body});emit("notice",`Importação ${r.state}: ${r.accepted_count} aceitos / ${r.rejected_count} rejeitados.`);await load();}catch(e){emit("error",msg(e));}}
async function showIssues(run:Row){try{const r=await props.api.request<Row>(`/government-education/validations/${run.id}/issues`);issues.value=r.items||[];}catch(e){emit("error",msg(e));}}
async function download(path:string,filename:string){try{const response=await props.api.response(path);const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}catch(e){emit("error",msg(e));}}
async function transmit(row:Row){try{const connection=connections.value[0]?.id||null;const r=await props.api.request<Row>(`/government-education/exports/${row.id}/transmissions`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":`gov-${row.id}-${crypto.randomUUID()}`},body:JSON.stringify({connection_id:connection})});emit("notice",r.state==="queued"?"Transmissão enviada para a fila do provider configurado.":"Exportação aguardando configuração de provider governamental.");await load();}catch(e){emit("error",msg(e));}}
async function retry(row:Row){try{await props.api.request(`/government-education/transmissions/${row.id}/retry`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Reprocessamento solicitado pelo operador autorizado"})});emit("notice","Transmissão governamental reavaliada/reprocessada.");await load();}catch(e){emit("error",msg(e));}}
onMounted(load);
</script>
<template><div class="government-panel">
<section class="grid-2 forms"><form class="panel" @submit.prevent="createLayout"><h2>Layout oficial versionado</h2><div class="cols"><label>Autoridade<select v-model="layoutForm.authority"><option>INEP</option><option>MEC</option><option>EDUCACENSO</option></select></label><label>Código<input v-model="layoutForm.layout_code" required></label></div><div class="cols"><label>Versão<input v-model="layoutForm.version" required></label><label>Vigência<input v-model="layoutForm.effective_from" type="date" required></label></div><label>Campos/regras do layout (JSON)<textarea v-model="layoutForm.fields_json" rows="7" spellcheck="false"></textarea></label><button class="primary">Registrar layout</button></form>
<form class="panel" @submit.prevent="validate"><h2>Validar / gerar exportação</h2><label>Layout<select v-model="runForm.layout_id" required><option v-for="l in layouts" :key="l.id" :value="l.id">{{l.authority}} · {{l.layout_code}} · {{l.version}}</option></select></label><label>Período<input v-model="runForm.reference_period" required></label><label>Registros (JSON)<textarea v-model="runForm.records_json" rows="8" spellcheck="false"></textarea></label><div class="row-actions"><button>Validar</button><button type="button" class="primary" @click="generateExport">Gerar CSV</button></div></form></section>
<section class="grid-2 forms"><form class="panel" @submit.prevent="uploadImport"><h2>Importar arquivo oficial</h2><label>Layout<select v-model="importForm.layout_id" required><option v-for="l in layouts" :key="l.id" :value="l.id">{{l.authority}} · {{l.layout_code}} · {{l.version}}</option></select></label><label>Período<input v-model="importForm.reference_period" required></label><label>CSV<input type="file" accept=".csv,text/csv" required @change="importFile=($event.target as HTMLInputElement).files?.[0]||null"></label><button class="primary">Validar e importar</button></form><div class="panel"><h2>Inconsistências</h2><table><thead><tr><th>Linha</th><th>Campo</th><th>Código</th><th>Mensagem</th></tr></thead><tbody><tr v-for="i in issues" :key="i.id||`${i.row_number}-${i.field_code}-${i.code}`"><td>{{i.row_number||'—'}}</td><td>{{i.field_code||'—'}}</td><td>{{i.code}}</td><td>{{i.message}}</td></tr><tr v-if="!issues.length"><td colspan="4" class="empty">Selecione uma validação para consultar inconsistências.</td></tr></tbody></table></div></section>
<section class="panel"><div class="panel-title"><h2>Validações e importações</h2><span>{{validations.length}} validações</span></div><table><thead><tr><th>Período</th><th>Direção</th><th>Estado</th><th>Registros</th><th>Erros</th><th></th></tr></thead><tbody><tr v-for="v in validations" :key="v.id"><td>{{v.reference_period}}</td><td>{{v.direction}}</td><td><span class="pill" :class="v.state==='valid'?'ok':'danger'">{{v.state}}</span></td><td>{{v.record_count}}</td><td>{{v.error_count}}</td><td><button class="small" @click="showIssues(v)">Inconsistências</button></td></tr></tbody></table><div class="notice-list"><article v-for="i in imports.slice(0,8)" :key="i.id"><strong>{{i.original_filename}}</strong><p>{{i.reference_period}} · {{i.state}} · {{i.accepted_count}} aceitos / {{i.rejected_count}} rejeitados</p><small>SHA-256 {{i.sha256}}</small><button class="small" @click="download(`/government-education/imports/${i.id}/download`,i.original_filename)">Baixar original</button></article></div></section>
<section class="panel"><div class="panel-title"><h2>Exportações e transmissões</h2><span>{{exports.length}} artifacts</span></div><table><thead><tr><th>Autoridade/layout</th><th>Período</th><th>Estado</th><th>SHA-256</th><th>Protocolo</th><th>Ações</th></tr></thead><tbody><tr v-for="e in exports" :key="e.id"><td>{{e.authority}} / {{e.layout_code}} · {{e.layout_version}}</td><td>{{e.reference_period}}</td><td><span class="pill">{{e.state}}</span></td><td><code>{{String(e.sha256).slice(0,16)}}…</code></td><td>{{e.protocol||'—'}}</td><td class="row-actions"><button class="small" @click="download(`/government-education/exports/${e.id}/download`,`government-${e.id}.csv`)">Baixar</button><button class="small" @click="transmit(e)">Transmitir</button></td></tr></tbody></table><h3>Fila / protocolos</h3><table><thead><tr><th>Export</th><th>Ambiente</th><th>Estado</th><th>Tentativas</th><th>Protocolo</th><th></th></tr></thead><tbody><tr v-for="t in transmissions" :key="t.id"><td><code>{{String(t.export_id).slice(0,8)}}…</code></td><td>{{t.environment}}</td><td><span class="pill" :class="t.state==='accepted'?'ok':t.state==='rejected'||t.state==='failed'?'danger':'warn'">{{t.state}}</span></td><td>{{t.attempts}}</td><td>{{t.protocol||'Aguardando retorno real'}}</td><td><button v-if="!['accepted','transmitting'].includes(t.state)" class="small" @click="retry(t)">Reprocessar</button></td></tr></tbody></table><p class="empty">A plataforma nunca marca transmissão oficial como aceita sem protocolo retornado pelo provider configurado.</p></section>
</div></template>
